/**
 * DPIIT / government industry sectors — Company registration (spec v1.0).
 * Alphabetically sorted except "Others" last.
 */
const _RAW = [
  'Agriculture & Cooperation',
  'Agriculture and Allied Sectors',
  'AI / ML',
  'Animal Husbandry & Fishing',
  'AR / VR',
  'Art & Culture',
  'Art and Handicrafts',
  'Automobile Sector',
  'Chemicals & Fertilizers',
  'Coal & Mine',
  'Commerce & Industry',
  'Communications & Information Technology',
  'Construction / Architecture / Proptech',
  'Defence',
  'Drone Technology',
  'E-commerce',
  'E-Vehicle',
  'Education & Training',
  'Edu-Tech',
  'Employment & Labour',
  'Energy & Power',
  'Environment & Natural Resources',
  'Environment and Waste Management',
  'Fashion and Apparels',
  'Finance, Banking & Insurance',
  'Finance and Allied Sectors',
  'FMCG',
  'Food & Public Distribution',
  'Food Processing',
  'Forestry & Wildlife',
  'Governance & Administration',
  'Health & Family Welfare',
  'Healthcare',
  'Home Affairs & National Security',
  'HORECA',
  'Housing & Urban Development',
  'HR Services',
  'Information & Broadcasting',
  'International Affairs',
  'IoT / ICT',
  'IT / ITeS',
  'Law & Justice',
  'Manufacturing / Industrial Automation',
  'Media and Entertainment',
  'Packaging and Logistics',
  'People & Organisations',
  'Petroleum, Oil & Natural Gas',
  'Robotics Technology',
  'Rural Development & Panchayati Raj',
  'Science, Technology & Research',
  'Social Justice & Empowerment',
  'Tourism',
  'Transport & Infrastructure',
  'Travel / Tourism & Hospitality',
  'Urban Transportation',
  'Youth Affairs & Sports',
  'Others',
] as const

const _OTHERS = 'Others'
const _rest = _RAW.filter((s) => s !== _OTHERS)
export const DPIIT_INDUSTRY_SECTORS: readonly string[] = [
  ...[..._rest].sort((a, b) => a.localeCompare(b, undefined, { sensitivity: 'base' })),
  _OTHERS,
]
