import { OTHER_OPTION_VALUE } from '@/constants/registrationLists'

export const REGISTRATION_COLLEGES_BY_UNIVERSITY: Record<string, string[] | null> = {
  'Babasaheb Bhimrao Ambedkar Bihar University (BRABU), Muzaffarpur': [
    '(Directorate of Distance Education), B. R. Ambedkar Bihar University, Muzaffarpur',
    'A.P.J. Abdul Kalam Degree Mahavidyalaya, Pakdi Devraj, RamNagar, West Champaran',
    'Abha Degree College, Dariyapur, kafen, kurhani, Muzaffarpur',
    'Ache Lal Singh Asarfi Devi Degree College, Bhagwanpur, Vaishali',
    'Adarsh Champaran Degree Mahavidyalay, Kotwa, East Champaran',
    'Akshaywat College, Mahua, Vaishali',
    'Arya College, Jahangirpur Salkhanni, Vaishali',
    'Asha College Of Professional Studies, East Champaran',
    'Asharfi Kunwar Ramratan Rai Mahavidyalaya, Kotwa Road, East Champaran',
    'Awadh Bihari Singh College, Lalganj, Vaishali',
    'B.M.D.College, Dayalpur, Vaishali',
    'B.M.T.T. College, Motihari',
    'Baba Bhagwat Rai Degree Mahavidyalaya, Telhua, Nautan, West Champaran',
    'Baba Bhootnath Mahavidyalay, Bagaha',
    'Babasaheb Bhimrao Ambedkar College, Jharharwa, Valmiki Nagar, West Champaran',
    'Bhagwan Mahavir Mahavidyalaya, Basokund, Saraiya, Muzaffarpur',
    'Bhagwati Shanti College, Loma, Rajapakar',
    'Birchand Patel Smarak College, Desari, Vaishali',
    'Bishwanath Roy Degree College, Nirpur, Patepur, Vaishali',
    'Biyog Lal Chaudhary Degree College, Jandaha, Vaishali',
    'C.N. College, Sahebganj, Muzaffarpur',
    'C.R.K College of Pharmacy, Hajipur, Vaishali',
    'Champaran Group of Institutions, Marjadawa-Parsa, West Champaran',
    'Chaurasia Raj Kishore Degree College, Hajipur',
    'Deo Chand College, Hajipur, Vaishali',
    'Dhanraj Bhagat Degree Mahavidyalaya, Mustafaganj, Minapur, Muzaffarpur',
    'Dr. Indal Singh Ram Janki Degree College, Parihar, Sitamarhi',
    'Dr. Jagannath Mishra College, Muzaffarpur',
    'Dr. K.K.P.Rai College, Hasampur, Mahnar',
    'Dr. R.M.L.S. College, Muzaffarpur',
    'Dr. Shri Krishn Sinha Women\'s College, Motihari',
    'Dr.Ganesh Ray Degree College, Sitamarhi',
    'Dr.Ram Balak Rai College, Hajipur, Vaishali',
    'Exalt College, Kanhauli, Mahua Road, Hajipur, Vaishali',
    'G.B. Chokhani College, Muzaffarpur',
    'Geeta Prasad Singh College of Commerce (Sandhyakalin) Mahavidyalaya, Muzaffarpur',
    'Giridharan Mishra Hari Shankar Pathak College, Bagaha',
    'H.T.M. College, Hardia, Narkatiaganj',
    'Hare Krishna Singh College, Hasanpur (Khopi), Vaishali',
    'Indu Devi Ranjeet Kumar Prakash Professional College, (Sandhyakalin) Hajipur',
    'Indu Devi Ranjeet Kumar Prakash Professional College, Hajipur',
    'Indudevi Ranjeet Kumar Prakash College (Sandhyakalin) Hajipur, Vaishali',
    'Institute of Degree College, Ramnagar, West Champaran',
    'Ishwar Shanti Mahavidyalay, Bettiah, West Champaran',
    'Islamia Degree Mahavidyalaya, Shahpur, Kanti, Muzaffarpur',
    'J.B.S.D. College, Bakuchi, Muzaffarpur',
    'J.L.N.M. College, Ghorasahan, E.Champaran',
    'J.M. Institute of Speech & Hearing',
    'J.S. College, Chandauli',
    'Jai Murat Rai Degree Mahavidyalaya, Nirpur, Patepur, Vaishali',
    'Jamuni Lal College, Hajipur',
    'Jawahar Lal Nehru Memorial College, Nawahi, Sursand, Sitamarhi',
    'Jeewachh College, Motipur, Muzaffarpur',
    'JRA Degree College Ishanpura, (Keshopur) Balukaram, Vaishali',
    'K.C.T.C. College, Raxaul, E.Champaran',
    'K.S.R.N.S Degree College, Mathiya, Kesariya, East Champaran',
    'Kanchan Kumar Karamveer Shivdayal Ray College, Vaishali',
    'L.N. College, Bhagwanpur, Vaishali',
    'L.N.D. College, Motihari',
    'L.N.T.College, Muzaffarpur',
    'L.P. Shahi Mahavidyalaya, Muzaffarpur',
    'L.S.College, Muzaffarpur',
    'Lalganj College, Lalganj, Vaishali',
    'LAXMI DEVI SACHCHIDANAND SINGH EVE. DEG. COLLEGE',
    'Laxmidevi Ramsurat Ray Degree College, Gavsara, Rewa Road, Muzaffarpur',
    'M.D.D.M College, Muzaffarpur',
    'M.J.K. College, Bettiah',
    'M.P.S. Science College, Muzaffarpur',
    'M.S. College, Motihari',
    'M.S.K.B. College, Muzaffarpur',
    'M.S.S.G. College, Areraj, E.Champaran',
    'Maharani Geeta Prabhat Degree College, Bhikhanpur, Mahnar, Vaishali',
    'Mahatma Gandhi Antarrashtriya VIdyapeeth Bharaulia, Motihari, East Champaran',
    'Mahavir Upadhyay Memorial Degree College, Dhaka, East Champaran',
    'Mahesh Prasad Singh Snatak Mahavidyalaya, Bela, Muzaffarpur',
    'Maheshwar Prasad Shahi College, Sitamarhi',
    'Maheshwarnath Mahamaya Mahila College, Bettiah',
    'Makhdum Bakhash Memorial Degree College, Uttarvahini, Chanpatiya, West Champaran',
    'Matashri Kaushalya Ramdev Dr. Ganesh Ray Degree College, Sitamarhi',
    'Meena Baskit Rai Mahavidyalaya, Yadav-Nagar, Basara, Rajapakar, Vaishali',
    'Muneshwar Singh Muneshwari Samta Mahavidyalaya, Jandaha, Vaishali',
    'Muzaffarpur College of Professional Education, Narsinghpur, Muzaffarpur',
    'N.G.M. Degree Mahavidyalaya, Bhelahi, East Champaran',
    'Narottam Mishra Memorial College, Narwara, Sheohar',
    'Nirmala Devi Ajay Maskara Sandhya Degree College, Raxaul',
    'Nirsu Narayan College, Singhara, Vaishali',
    'Nitesh Kumar Smarak College, Paharpur Toi, Sahdei Buzurg, Vaishali',
    'Nitishwar Ayurved Medical College & Hospital, Kanhauli, Muzaffarpur',
    'Nitishwar Mahavidyalaya, Muzaffarpur',
    'Nitishwar Singh Degree Mahavidyalaya, Sarmastpur',
    'Orakh Thakur Memorial Degree Mahavidyalaya, Motipur, Sandha, Muzaffarpur',
    'Pandit Ujjwal Kumar Mishra Foundation College, (Sandhyakalin) Hajipur, Vaishali',
    'Pawan Kumar Jha Degree College, Loma, Hajipur',
    'Priya Rani Rai Degree College, Bairgania, Sitamarhi',
    'PT. DDU EVE. COLLEGE, BAIRGANIA',
    'Pt. Ugam Pandey College, Motihari',
    'Pt. Ujjwal Kumar Mishra Foundation College Hajipur, Vaishali',
    'Pt. Uma Shankar Tiwari Mahila College',
    'Pt. Vedanand Umesh Mishra RamJanki College, (Sandhyakalin), Mahua, Vaishali',
    'Pt. Vedanand Umesh Mishra RamJanki College, Mahua, Vaishali',
    'Pt. Yamuna Karji College, Bagahi, Kharauna, Dholi, Muzaffarpur',
    'R.B.B.M College, Muzaffarpur',
    'R.C. College, Sakra, Muzaffarpur',
    'R.D.S. College, Muzaffarpur',
    'R.L.S.Y.College, Bettiah',
    'R.N. College, Hajipur',
    'R.P.S. College, Chakeyaj, Vaishali',
    'R.R. SAH COLLEGE, RAXAUL, East CHAMPARAN',
    'R.S.S. Mahila College, Sitamarhi',
    'R.S.S. Science College, Sitamarhi',
    'Raghunath Jha Degree Mahavidyalaya, Sitamarhi',
    'Rai Birendra Singh College, Kutubpur Ekara, Vaishali',
    'Rajeev College of Pharmacy, Dhanhara, Sitamarhi',
    'Rajendra Mahavidyalaya, Chapra',
    'Rajkeshwar Rao Nandangarh Degree College, Bijbaniya, Lauriya, West Champaran',
    'Rajkiya Degree Mahavidyalaya, Bagha, West Champaran',
    'Rajkiya Degree Mahavidyalaya, Pakridayal, East Champaran',
    'Rajkiya Degree Mahavidyalaya, Sheohar',
    'Rajvanshi Ramashish College of Pharmacy, Harauli, Vaishali',
    'Ram Bilas Ganga Ram College, Maharajganj Siwan',
    'Ram Lagan Rai Degree College, Rajapakar, Vaishali',
    'Ram Sharan Roy College, Panapur, Makkanpur, Jandaha, Vaishali',
    'Ram Sharan Roy College, Panapur, Makkanpur, Vaishali',
    'Rambilas Singh Ramdayal Roy College, Saraipur, Raghopur, Vaishali',
    'Rameshwar Mahavidyalaya, Muzaffarpur',
    'Rameshwar Mahavir Evening Degree College, Harsidhi, East Champaran',
    'Ramshresta Singh College, Chochaha, Belsar, Muzaffarpur',
    'RDRD College, Kiratpur, Rajaram',
    'Ritlal Surdeep Yadav Degree Mahavidyalaya, Muzaffarpur',
    'S. K. Yadav Degree College, Tajpur Patkholia, Kesaria, East Champaran',
    'S.L.K. College, Sitamarhi',
    'S.M.S.J. Ayurved College & Hospital',
    'S.M.V.D College, Kalyanpur, East Champaran',
    'S.N.S. College, Hajipur',
    'S.N.S. College, Motihari',
    'S.R.A.P. College, Barachakia, E.Champaran',
    'S.R.K.G. College, Sitamarhi',
    'S.R.P.S. College, Jaintpur, Muzaffarpur',
    'Sanskar Bharti School of Education, West Champaran',
    'Saraswati Balram Singh College, Vaishali',
    'Satyendra Narayan Singh Mahavidhalaya, Hajipur, Vaishali',
    'seyabati Lalmuni Degree, Pattepur, Vaishali',
    'Shiv Shakti College, Bhatauliya, Pokhraira, Muzaffarpur',
    'Shree Babulal Ray Sumitra Sinha Degree College, Goraul, Vaishali',
    'Shri Umesh Mishra Ranjeet Kumar Prakash College (Sandhyakalin), Hajipur, Vaishali',
    'Shri Umesh Mishra Ranjeet Kumar Prakash College, Hajipur, Vaishali',
    'Shukdeo Mukhlal Degree College, Hajipur, Vaishali',
    'Shyam Narayan Singh Ram Narayan Singh Degree College, Dharmaha, keshariya, East Champaran',
    'Shyamnandan Sahay College, Muzaffarpur',
    'Sri Ram Janki Swami Sahajanand Saraswati Snatak Mahavidyalaya',
    'St. Joseph\'s Management College',
    'T.P. Verma College, Narkatiaganj, W.Champaran',
    'Tharuhat Mahavidyalaya, Harnatand, Kerai, Naurangiya, Paschim Champaran',
    'Urmila Devi Sadanand Yadav Gurukul Degree College, Dumra, Sitamarhi',
    'Vaishali Mahila College, Hajipur',
    'Yamuna Nand Kishore Shukla College, Hajipur',
  ],
  'Bhupendra Narayan Mandal University (BNMU), Madhepura': [
    'Adarsh College, Madhepura',
    'Anooplal Yadav Mahavidyalaya, Supaul',
    'B S S Chandrakanta College, Madhepura',
    'B.S.R.K. College, Madhepura',
    'Banwari Shankar College, Saharsa',
    'Bharat Sevak Samaj College, Supaul',
    'Bhupendra Narayan Mandal Vanijya Mahavidyalaya, Madhepura',
    'C. M. Science Degree College, Madhepura',
    'Degree College Supaul, Supaul',
    'Deo Nandini Degree College, Madhepura',
    'East N West Teachers Training College, Saharsa',
    'Evening College Saharsa, Saharsa',
    'Evening College, Madhepura',
    'Hari Prasad Sah College, Supaul',
    'Harihar Saha College, Madhepura',
    'K.B. Womens College, Madhepura',
    'K.N. Degree College, Supaul',
    'Kamla Rana Science College, Madhepura',
    'Kamleshwari Prasad College, Madhepura',
    'Lahtan Choudhary College Pastwar, Saharsa',
    'Lalit Narayan Mishra Smarak College, Supaul',
    'Laxmi Nath College, Saharsa',
    'Madhepura College Madhepura, Madhepura',
    'Maharaja Hariballav Memorial College, Saharsa',
    'Manohar Lal Tekriwal College, Saharsa',
    'Mohan Shakuntala Teacher‘s Training College, Madhepura',
    'Parwati Science College, Madhepura',
    'R.M.M. Law College, Saharsa',
    'Radhe Shyam Teacher\'s Training College, Supaul',
    'Rajendra Mishra College, Saharsa',
    'Ramesh Jha Mahila College, Saharsa',
    'Ranchandra Vidyapith, Saharsa',
    'Rpm College, Madhepura',
    'S.N.S. Mahila College, Supaul',
    'Sant Awadh Kiriti Narayan Degree College, Madhepura',
    'Sarb Narayan Singh Ram Kumar Singh College, Saharsa',
    'Shivnandan Prasad Mandal Law College, Madhepura',
    'Subhash Chandra Bose College Of Education, Madhepura',
    'Thakur Prasad College, Madhepura',
    'U V K College, Madhepura',
    'Women’s College, Madhepura',
  ],
  'Bihar Engineering University (BEU), Patna': [
    'Adwaita Mission Institute of Technology, Banka',
    'B. P. Mandal College of Engineering, Madhepura',
    'Bakhtiyarpur College of Engineering, Patna',
    'Bhagalpur College of Engineering, Bhagalpur',
    'Buddha Institute of Technology, Gaya',
    'Central Institute of Petrochemicals Engineering & Technology (CIPET), Patna (Bihta)',
    'Darbhanga College of Engineering, Darbhanga',
    'Dr. Ashok Gagan College, Bihta, Patna',
    'Exalt College of Engineering & Technology, Vaishali',
    'Gaya College of Engineering, Gaya',
    'Government Engineering College, Arwal',
    'Government Engineering College, Aurangabad',
    'Government Engineering College, Banka',
    'Government Engineering College, Bhojpur',
    'Government Engineering College, Buxar',
    'Government Engineering College, Gopalganj',
    'Government Engineering College, Jamui',
    'Government Engineering College, Jehanabad',
    'Government Engineering College, Kaimur',
    'Government Engineering College, Khagaria',
    'Government Engineering College, Kishanganj',
    'Government Engineering College, Lakhisarai',
    'Government Engineering College, Madhubani',
    'Government Engineering College, Munger',
    'Government Engineering College, Nawada',
    'Government Engineering College, Samastipur',
    'Government Engineering College, Sheikhpura',
    'Government Engineering College, Sheohar',
    'Government Engineering College, Siwan',
    'Government Engineering College, Vaishali',
    'Government Engineering College, West Champaran',
    'Hi-Tech Polytechnic College, West Champaran (Bettiah)',
    'Institute of Management and Planning & Advanced Computer Training, Patna',
    'J. P. College of Engineering, Biharsharif, Nalanda',
    'Katihar Engineering College, Katihar',
    'Lok Nayak Jai Prakash Institute of Technology, Saran (Chapra)',
    'Maulana Azad College of Engineering and Technology, Neora, Patna',
    'Millia Institute of Technology, Purnea',
    'Millia Kishanganj College of Engineering & Technology, Kishanganj',
    'Mother\'s Institute of Technology, Bihta, Patna',
    'Motihari College of Engineering, East Champaran',
    'Muzaffarpur Institute of Technology, Muzaffarpur',
    'Nalanda College of Engineering, Chandi, Nalanda',
    'Netaji Subhas Institute of Technology, Bihta, Patna',
    'Prabhu Kailash Engineering College, Aurangabad',
    'Purnea College of Engineering, Purnea',
    'R. P. Sharma Institute of Technology, Patna',
    'Rajeev College of Professional Education, Sitamarhi',
    'Rashtrakavi Ramdhari Singh Dinkar College of Engineering, Begusarai',
    'Rungta Institute of Technology and Management, Araria',
    'Saharsa College of Engineering, Saharsa',
    'Sershah College of Engineering, Rohtas (Sasaram)',
    'Shri Phanishwar Nath Renu Engineering College, Araria',
    'Sitamarhi Institute of Technology, Sitamarhi',
    'Sityog Institute of Technology, Aurangabad',
    'Siwan College of Engineering and Management, Siwan',
    'Supaul College of Engineering, Supaul',
    'Vidya Vihar Institute of Technology, Purnea',
  ],
  'Board of Technical Education Uttar Pradesh (BTEUP), Lucknow': [
    'A.C.E. College of Engineering and Management',
    'A.C.N. College of Polytechnic',
    'A.D.R.S. Institute of Technology and Management',
    'A.N.A. College of Engineering and Management Studies, Bareilly',
    'A.S.M. Polytechnic',
    'ABSS Institute of Technology',
    'Academy of Technology Management & Science',
    'Accurate Institute of Polytechnic',
    'Acharya Baldev Polytechnic College',
    'Adarsh Polytechnic College, Siddharth Nagar',
    'Adarsh Polytechnic, Ghazipur',
    'Adhunik College of Engineering',
    'Aeronautical Training Institute',
    'Allahabad College of Engineering & Management',
    'Allenhouse Institute of Technology',
    'Amardeep Polytechnic College',
    'Ambition Institute of Technology',
    'Anand Polytechnic College',
    'Anjana Institute of Technical Education',
    'Apex Institute of Technology',
    'Apollo Institute of Technology',
    'Aryan Institute of Technology',
    'Aryavart Institute of Technology & Management',
    'Aryika Gyanwati Government Girls Polytechnic, Faizabad',
    'Ashoka Institute of Technology & Management',
    'Asian Institute of Rural Technology',
    'Asian Institute of Science and Technology',
    'Axis Inst. of Diploma Engineering',
    'Axis Institute of Fashion Technology',
    'Axis Institute of Technology and Management',
    'Azad Institute of Engineering & Technology',
    'Azad Polytechnic',
    'B.K. Polytechnic',
    'B.N. College of Engineering & Technology (BNCET)',
    'B.R. Gautam Polytechnic',
    'B.S.A. College of Engineering & Technology',
    'Baba Bindeshwari Singh Inst. of Technology & Management',
    'Baba Ramdal Sooraj Dev Polytechnic College',
    'Baba Saheb Dr. Bhimrao Ambedkar Government Polytechnic, Auraiya',
    'Baba Vishwanath Institute of Technology',
    'Baba Vishwanath Technical Institute, Deoria',
    'Babu Banarsi Das Institute of Engineering Technology & Research Centre',
    'Babu Banarsi Das Northern India Institute of Technology',
    'Babu Sunder Singh Institute of Technology and Management',
    'Babu Sushil Singh Institute of Polytechnic',
    'Baijnath Ramnaresh College of Technology',
    'Bakshi Polytechnic',
    'Banaras Institute of Polytechnic & Engineering',
    'Beacon Institute of Technology',
    'Bhagwant Institute of Technology',
    'Bhaskar Polytechnic College',
    'Bhavya Technical Institute',
    'Bhonwal School of Engineering',
    'Buddha Institute of Technology',
    'Buddha Polytechnic College',
    'C.B.S. College of Polytechnic',
    'Chandauli Polytechnic, Chandauli',
    'Chandradev Memorial Polytechnic College, Ballia',
    'Chatrapati Sahuji Maharaj Government Polytechnic, Ambedkar Nagar',
    'Chatrapati Sahuji Maharaj Government Polytechnic, Balrampur',
    'Chaudhary Institute of Technology, Ballia',
    'Chaudhry Mukhtar Singh Government Girls Polytechnic, Daurala, Meerut',
    'Chhatrapati Shahuji Maharaj College of Engineering & Technology',
    'College of Engineering & Rural Technology',
    'D.N.M. Institute of Engineering and Technology',
    'D.N.S. College of Engineering & Technology',
    'Delhi Institute of Engineering & Technology',
    'Dev Indrawati Institute of Polytechnic, Ambedkar Nagar',
    'Dev Institute of Technical Education',
    'Dev Naagri Polytechnic, Meerut',
    'Dev Technical Campus',
    'Devbhumi Institute of Polytechnic',
    'Devo Mahesh College of Engineering and Technology',
    'Devrishi Institute of Polytechnic and Technology',
    'Digamber Jain Polytechnic',
    'Dr. Ambedkar Institute of Technology for Handicapped, Kanpur',
    'Dr. B.R. Ambedkar Polytechnic',
    'Dr. B.R. Ambedkar Polytechnic College',
    'Dr. Dashrath Chaudhary Institute of Technology, Bansi, Siddhartha Nagar',
    'Dr. K.N. Modi Engineering College',
    'Dr. M.C. Saxena Polytechnic',
    'Dr. Rajesh Polytechnic Institute, Ghazipur',
    'Dr. Rizvi College of Engineering',
    'Dr. Vijay Institute of Education & Technology',
    'Dreams College of Polytechnic',
    'Edifi Institute of Polytechnic',
    'Emerald-9 Institute of Management and Technology, Barabanki',
    'Eshan College of Engineering',
    'F.I.T. Engineering College',
    'Feroze Gandhi Polytechnic',
    'Future Institute of Engineering and Technology',
    'G. B. Pant Polytechnic',
    'G.C.R.G. College of Polytechnic',
    'Gajraj Singh Polytechnic',
    'Gandhi Institute of Engineering and Technology',
    'Gandhi Polytechnic, Muzaffarnagar',
    'Gayatri College of Engineering & Technology',
    'Goel Institute of Technology & Management',
    'Gokaran Narvadeshwar Institute of Technology and Management',
    'Government Girls Polytechnic, Allahabad',
    'Government Girls Polytechnic, Amethi',
    'Government Girls Polytechnic, Arnia, Bulandshahr',
    'Government Girls Polytechnic, Atarauli, Aligarh (PPP Mode)',
    'Government Girls Polytechnic, Bahraich (PPP Mode)',
    'Government Girls Polytechnic, Ballia',
    'Government Girls Polytechnic, Bareilly',
    'Government Girls Polytechnic, Basti (PPP Mode)',
    'Government Girls Polytechnic, Charkhari, Mahoba',
    'Government Girls Polytechnic, Gorakhpur',
    'Government Girls Polytechnic, Lucknow',
    'Government Girls Polytechnic, Meza, Allahabad',
    'Government Girls Polytechnic, Moradabad',
    'Government Girls Polytechnic, Risiya Nanpara, Bahraich',
    'Government Girls Polytechnic, Sadar, Mirzapur',
    'Government Girls Polytechnic, Shamli',
    'Government Girls Polytechnic, Tilhar, Shahjahanpur',
    'Government Girls Polytechnic, Varanasi',
    'Government Leather Institute, Agra',
    'Government Leather Institute, Kanpur',
    'Government Polytechnic (PPP Mode), Kulpahad, Mahoba',
    'Government Polytechnic, Adampur, Tarabganj, Gonda',
    'Government Polytechnic, Alapur, Budaun',
    'Government Polytechnic, Aliya, Sitapur',
    'Government Polytechnic, Atraulia, Azamgarh (PPP Mode)',
    'Government Polytechnic, Aurai, Sant Ravidas Nagar',
    'Government Polytechnic, Baberu, Banda (PPP Mode)',
    'Government Polytechnic, Bachhrawan, Raebareli',
    'Government Polytechnic, Baheri, Bareilly',
    'Government Polytechnic, Bahraich',
    'Government Polytechnic, Baijpur Bhiti, Ambedkar Nagar',
    'Government Polytechnic, Bakshi Ka Talab, Lucknow',
    'Government Polytechnic, Banda',
    'Government Polytechnic, Banshdeeh',
    'Government Polytechnic, Bara',
    'Government Polytechnic, Barabanki',
    'Government Polytechnic, Bareilly',
    'Government Polytechnic, Bargarh, Chitrakoot',
    'Government Polytechnic, Basti',
    'Government Polytechnic, Bhanpur',
    'Government Polytechnic, Bhilihili, Azamgarh',
    'Government Polytechnic, Bighapur, Unnao',
    'Government Polytechnic, Bijnor',
    'Government Polytechnic, Bilsi, Budaun (PPP Mode)',
    'Government Polytechnic, Bindki, Fatehpur',
    'Government Polytechnic, Budaun',
    'Government Polytechnic, Chabilaha, Khor, Sadar, Basti',
    'Government Polytechnic, Chamraua, Rampur',
    'Government Polytechnic, Chandausi',
    'Government Polytechnic, Changipur, Noorpur, Bijnor',
    'Government Polytechnic, Chariyaon, Deoria',
    'Government Polytechnic, Chhachha Bhogaon, Mainpuri',
    'Government Polytechnic, Chhibramau, Kannauj (PPP Mode)',
    'Government Polytechnic, Chopan, Sonbhadra',
    'Government Polytechnic, Chunar, Mirzapur',
    'Government Polytechnic, Debai, Bulandshahr',
    'Government Polytechnic, Deeh, Sadar, Unnao',
    'Government Polytechnic, Deoria',
    'Government Polytechnic, Etawah',
    'Government Polytechnic, Faizabad',
    'Government Polytechnic, Fareedpur, Bareilly (PPP Mode)',
    'Government Polytechnic, Farrukhabad',
    'Government Polytechnic, Fatehpur',
    'Government Polytechnic, Firozabad',
    'Government Polytechnic, Ghatampur, Kanpur',
    'Government Polytechnic, Ghaziabad',
    'Government Polytechnic, Ghazipur',
    'Government Polytechnic, Ghosi, Mau',
    'Government Polytechnic, Ghughalpur, Balrampur (PPP Mode)',
    'Government Polytechnic, Gonda',
    'Government Polytechnic, Gopalpur, Salon, Raebareli',
    'Government Polytechnic, Gopamau, Hardoi',
    'Government Polytechnic, Gorakhpur',
    'Government Polytechnic, Hardoi',
    'Government Polytechnic, Hardoi, Sandila (PPP Mode)',
    'Government Polytechnic, Hindalpur, Hapur',
    'Government Polytechnic, Jamuniya Deeh, Harakh, Barabanki',
    'Government Polytechnic, Jansath, Muzaffarnagar',
    'Government Polytechnic, Jaunpur',
    'Government Polytechnic, Jhansi',
    'Government Polytechnic, Jigirsand, Sikandarpur, Ballia',
    'Government Polytechnic, Kadipur',
    'Government Polytechnic, Kaimganj, Farrukhabad',
    'Government Polytechnic, Kanpur',
    'Government Polytechnic, Katai Joya, Amroha',
    'Government Polytechnic, Kenaura, Sultanpur',
    'Government Polytechnic, Kirthal, Chaprauli, Baghpat',
    'Government Polytechnic, Kishni, Mainpuri',
    'Government Polytechnic, Kotwan, Mathura',
    'Government Polytechnic, Kurara, Hamirpur',
    'Government Polytechnic, Kursi Road, Barabanki',
    'Government Polytechnic, Kuru Pindra, Varanasi',
    'Government Polytechnic, Kutana, Baraut, Baghpat',
    'Government Polytechnic, Lakhimpur Kheri',
    'Government Polytechnic, Lalitpur',
    'Government Polytechnic, Lucknow',
    'Government Polytechnic, Madhogarh, Jalaun',
    'Government Polytechnic, Mahasi, Bahraich (PPP Mode)',
    'Government Polytechnic, Mahoba',
    'Government Polytechnic, Mainpuri',
    'Government Polytechnic, Manikpur, Chitrakoot',
    'Government Polytechnic, Mankera, Agra',
    'Government Polytechnic, Mau',
    'Government Polytechnic, Mawana Khurd, Meerut',
    'Government Polytechnic, Mirzapur',
    'Government Polytechnic, Mohammadi, Kheri',
    'Government Polytechnic, Mohammadpur, Bahraich',
    'Government Polytechnic, Moradabad',
    'Government Polytechnic, Mujahana, Hata, Kushinagar',
    'Government Polytechnic, Naraini, Banda',
    'Government Polytechnic, Orai (Jalaun)',
    'Government Polytechnic, Phoolpur Pawai, Azamgarh (PPP Mode)',
    'Government Polytechnic, Pilibhit',
    'Government Polytechnic, Pratapgarh',
    'Government Polytechnic, Premdharpatti, Pratapgarh',
    'Government Polytechnic, Puranpur, Pilibhit',
    'Government Polytechnic, Purena, Sadar, Maharajganj',
    'Government Polytechnic, Puwayan, Shahjahanpur',
    'Government Polytechnic, Rajgarh, Mirzapur',
    'Government Polytechnic, Rampur',
    'Government Polytechnic, Saharanpur',
    'Government Polytechnic, Sahjanwa, Gorakhpur (PPP Mode)',
    'Government Polytechnic, Sant Kabir Nagar',
    'Government Polytechnic, Sardhana, Meerut (PPP Mode)',
    'Government Polytechnic, Sarsai Rath, Hamirpur',
    'Government Polytechnic, Shahbad, Rampur',
    'Government Polytechnic, Shahjahanpur',
    'Government Polytechnic, Shamsabad, Agra',
    'Government Polytechnic, Sikandara Rao, Etah',
    'Government Polytechnic, Sikandara Rao, Hathras (PPP Mode)',
    'Government Polytechnic, Sikandra, Kanpur Dehat',
    'Government Polytechnic, Sinduria, Sonbhadra',
    'Government Polytechnic, Sonbhadra',
    'Government Polytechnic, Soron, Kasganj',
    'Government Polytechnic, Sumda, Sahaswan, Budaun',
    'Government Polytechnic, Sumerpur, Hamirpur',
    'Government Polytechnic, Sutawali, Amroha',
    'Government Polytechnic, Talbehat, Lalitpur',
    'Government Polytechnic, Thakurdwara, Moradabad',
    'Government Polytechnic, Tundla, Firozabad',
    'Government Polytechnic, Unnao',
    'Greater Noida Polytechnic College',
    'H.M.F.A. Memorial Institute of Engineering and Technology',
    'H.R. Institute of Engineering and Technology',
    'Handia Polytechnic, Handia',
    'Hanswahini Institute of Science & Technology',
    'Hardayal Technical Campus',
    'Hastinapur Institute of Technology and Management',
    'Hewett Polytechnic, Lucknow',
    'Himalayan Polytechnic Institute',
    'I.I.M.T. College of Polytechnic',
    'I.M.S. College of Polytechnic',
    'I.M.S. Polytechnic',
    'I.T.M. College of Polytechnic',
    'I.V.S. Polytechnic',
    'Indian Institute of Packaging, Lucknow',
    'Indramohan Chauhan Memorial Polytechnic',
    'Indraprastha Institute of Management and Technology',
    'Indu Prakash Polytechnic College',
    'Indus Institute of Technology and Management',
    'Ingraham Polytechnic, Hapur Road',
    'Institute of Engineering and Rural Technology, Prayagraj',
    'Institute of Technology & Management',
    'Institute of Technology & Management, Lucknow',
    'Institute of Technology and Management',
    'Institute of Technology and Management, Gorakhpur',
    'Institute of Tool Room Training, U.P., Lucknow',
    'J. P. Institute of Hotel Management & Catering Technology',
    'J.D. Institute of Engineering and Technology',
    'J.P. Institute of Engineering and Technology',
    'J.P. Institute of Technology & Management',
    'Jankalyan Institute of Technical Education',
    'Jannayak Late Babu Manager Singh Government Polytechnic, Bairiya, Ballia (PPP Mode)',
    'Janta Polytechnic, Jahangirabad',
    'Jaswant Singh Bhadauria Institute of Technology',
    'Jawahar Lal Nehru Polytechnic',
    'Jhunjhunwala P.G. College Faculty of Engineering and Technology',
    'JMS Institute of Technology',
    'Jyotiraditaya Institute of Technology Management and Research',
    'K.I.P.M. College of Engineering and Technology',
    'K.L. Polytechnic',
    'K.L.S. Polytechnic College',
    'K.P. Engineering and Technology',
    'Kalicharan Nigam Institute of Technology',
    'Kamal Institute of Technology',
    'Kanchan Polytechnic',
    'Kanpur Institute of Technology',
    'Kashi Institute of Technology',
    'Kashinath Institute of Polytechnic',
    'Kashinath Institute of Technology',
    'KCMT Campus 2 Prem Prakash Gupta Institute of Engineering',
    'Keshav Polytechnic',
    'KET Polytechnic Institute',
    'KM. Mayawati Government Girls Polytechnic, Badalpur, Gautam Buddha Nagar',
    'Krishna Institute of Polytechnic, Bijnor',
    'L.D.C. Institute of Technical Studies',
    'Lakshya Technical Campus',
    'Lal Bahadur Shastri Polytechnic, Manda Mauja Girdharpur, Allahabad',
    'Lalsa Institute of Engineering & Rural Technology',
    'Landmark Technical Campus',
    'Little Flower Polytechnic',
    'Lloyd Institute of Management and Technology',
    'Lucknow Institute of Technology',
    'Lucknow Polytechnic, Lucknow',
    'Lutawan Institute of Technology and Management',
    'M.G. Institute of Management & Technology',
    'M.G. Polytechnic',
    'M.G.A. Institute of Polytechnic',
    'M.I.T. Institute of Technology',
    'M.S.D. Polytechnic College',
    'Maa Bhagwata Kunwar Institute of Polytechnic',
    'Maa Buddha National Institute of Engg. & Technology',
    'Maa Saraswati Science and Technology, Ballia',
    'Maa Sharda Institute of Technology',
    'Maa Vaishnav Maa Sharda Polytechnic',
    'Mahakarunik Tathagat Gautam Buddha Government Polytechnic, Siddhartha Nagar',
    'Mahalwar Institute of Technology',
    'Mahamanav Gautambuddha Polytechnic',
    'Mahamaya Polytechnic of Information Technology, Aligarh',
    'Mahamaya Polytechnic of Information Technology, Amroha',
    'Mahamaya Polytechnic of Information Technology, Auraiya',
    'Mahamaya Polytechnic of Information Technology, Chandauli',
    'Mahamaya Polytechnic of Information Technology, Hariharpur, Gorakhpur',
    'Mahamaya Polytechnic of Information Technology, Kannauj',
    'Mahamaya Polytechnic of Information Technology, Kanpur Dehat',
    'Mahamaya Polytechnic of Information Technology, Kasganj',
    'Mahamaya Polytechnic of Information Technology, Kaushambi',
    'Mahamaya Polytechnic of Information Technology, Kushinagar',
    'Mahamaya Polytechnic of Information Technology, Mahamaya Nagar, Hathras',
    'Mahamaya Polytechnic of Information Technology, Maharajganj',
    'Mahamaya Polytechnic of Information Technology, Sant Kabir Nagar',
    'Mahamaya Polytechnic of Information Technology, Shamli',
    'Mahamaya Polytechnic of Information Technology, Shravasti',
    'Mahamaya Polytechnic of Information Technology, Siddharth Nagar',
    'Maharaja Agrasen College of Engineering and Technology',
    'Maharana Institute of Technology & Sciences',
    'Maharana Pratap College of Engineering',
    'Maharana Pratap Polytechnic, Gorakhpur',
    'Maharishi Patanjali Polytechnic of Information Technology',
    'Mahatma Jyotiba Phule Government Polytechnic, Kaushambi',
    'Mahaveer Institute of Technology',
    'Manyawar Kanshiram Dasairam Polytechnic',
    'Manyawar Kanshiram Government Polytechnic, Kannauj',
    'Manyawar Kanshiram Institute of Tourism Management',
    'Marathwada Institute of Technology',
    'Meerut Institute of Technology',
    'Meerut International Institute of Technology',
    'Modern College of Engineering',
    'Modinagar Institute of Technology',
    'Moradabad Polytechnic',
    'MSME Technology Centre, Kanpur',
    'Murlidhar Gajanan Polytechnic, Hathras',
    'Naraina College of Engineering and Technology',
    'Naraina Vidhyapeeth Engineering and Management Institute',
    'Narayana Polytechnic Institute',
    'NC Polytechnic',
    'Neelam College of Engineering & Technology',
    'Neelkanth Institute of Engg. & Tech.',
    'NIGC Institute of Technology and Management',
    'Nirmala Devi Polytechnic College',
    'Northern Region Institute of Printing Technology, Prayagraj',
    'P.C.P.S. College of Technology & Management',
    'P.K. Polytechnic',
    'Panchwati Institute of Polytechnic, Meerut',
    'Prabhat Engineering College',
    'Prasad Institute of Technology',
    'Prasad Polytechnic',
    'Prateek Singh Siddharth Polytechnic College, Siddharthnagar',
    'Prayag Institute of Technology and Management',
    'Prem Mahavidyalay Polytechnic, Mathura',
    'Prince Institute of Innovative Technology',
    'PSIT Polytechnic',
    'Pt. Ramadhar J. Tiwari College of Polytechnic',
    'R.B. Gautam Polytechnic',
    'R.K. Polytechnic',
    'R.N. Polytechnic',
    'R.P. Polytechnic College, Deoria',
    'R.R. Institute of Modern Polytechnic',
    'R.R. Polytechnic',
    'R.V. Institute of Technology',
    'Radha Govind Polytechnic College',
    'Radha Krishna Polytechnic College',
    'Radha Vallabh Institute of Technology',
    'Raj Narayan Singh Sammopur Polytechnic',
    'Raj Polytechnic, Siswa',
    'Raj Shree Institute of Management and Technology',
    'Raja Balwant Singh Polytechnic, Agra',
    'Rajiv Gandhi Polytechnic',
    'Rakshpal Bahadur College of Engineering and Technology',
    'Ram Singh College of Engineering & Technology',
    'Ram-Eesh Institute of Engineering & Technology',
    'Ram-Eesh Institute of Vocational & Technical Education',
    'Rameshwaram Institute of Technology & Management',
    'Regional Labour Institute',
    'Rishi Institute of Engineering and Technology',
    'Rishi Ramnaresh Technical Institute',
    'Robin College of Education and Technology, Meerut',
    'Rudra Polytechnic',
    'S.D. College of Engineering & Technology',
    'S.S. Bapu Institute of Polytechnic',
    'S.V.M. Technical Institute',
    'S.V.S. Polytechnic',
    'Sagar Institute of Technology and Management',
    'Sai Meer College of Polytechnic',
    'Samarth Institute for Education and Technology, Meerut',
    'SAMS Institute of Technology',
    'Sanjay Gandhi Polytechnic, Jagdishpur, Amethi',
    'Sanjivani Institute of Technology and Management',
    'Sanskar College of Engineering and Technology',
    'Sant Ravidas Government Polytechnic, Chakia, Chandauli',
    'Saraswati Higher Education and Technical College of Engineering',
    'Saraswati Institute of Engineering & Technology',
    'Sardar Vallabh Bhai Patel College of Polytechnic',
    'Saroj College of Engineering and Polytechnic',
    'Saroj Institute of Management and Technology',
    'Saroj Institute of Techno and Management',
    'Saroj Institute of Technology and Management',
    'Sarvodaya Polytechnic College',
    'Satyadev Institute of Technology',
    'Savitri Bai Phule Government Polytechnic, Azamgarh',
    'Savitribai Phule Government Girls Polytechnic, Saharanpur',
    'Seth Ganga Sagar Jatia Government Polytechnic, Khurja, Bulandshahr',
    'Seth Jaiprakash Mukundlal Polytechnic',
    'Seth Vishambharnath Institute of Engineering & Technology',
    'Sevdi Inst. of Management & Technology',
    'Shaheed Virendra Singh Sirohi Institute of Technology',
    'Shanti Institute of Technology',
    'Shanti Institute of Technology & Pharmacy (mixed institution)',
    'Shanti Polytechnic',
    'Shanti Polytechnic & Pharmacy (mixed institution)',
    'Shiva Polytechnic Institute of Management College',
    'Shivaji Institute of Technology & Management',
    'Shivdan Singh Institute of Techno and Management, Aligarh',
    'Shivdan Singh Institute of Technology & Management',
    'Shri Gopichand Institute of Management and Technology',
    'Shri Moti Smriti Institute of Technology',
    'Shri Tridandideo Hanumat Technical College, Bisupur, Khandwari, Chandauli',
    'Shri Vishwanath College of Polytechnic',
    'Shrimati Phulehra Smarak College of Polytechnic',
    'Shrinathji Institute for Technical Education',
    'Shriram Polytechnic',
    'Sitapur Shiksha Sansthan (School of Engineering & Technology)',
    'SNSK Institute of Technology',
    'Sri Anar Devi Khandelwal Mahila Polytechnic',
    'Sri Bhagwat Institute of Technology',
    'Sri Durgaji Polytechnic Institute, Sehda, Azamgarh',
    'Sri Giriraj Maharaj Polytechnic College',
    'Sri Ramdevi Ramdayal Tripathi Mahila Polytechnic',
    'Sri Sahdev Paudhariya Polytechnic College',
    'Sri Siddhi Vinayak Polytechnic',
    'Subharti Polytechnic College',
    'Sunrise Institute of Engineering Technology and Management',
    'Sureshdeep Polytechnic',
    'Surya Polytechnic for Engineering & Technology',
    'Suyash Institute of Information Technology',
    'Swami Kalyandev Polytechnic Institute',
    'Swami Sahjanand Polytechnic',
    'Tathagat Gautam Buddha Government Polytechnic, Shravasti',
    'Thakur Tej Bahadur Singh Institute of Technology, Karampur, Saidpur, Ghazipur',
    'Tirupati College of Engineering',
    'Town Polytechnic, Ballia',
    'Translam Institute of Technology & Management',
    'Udayraj Singh Rampyari Institute of Science and Technology',
    'Unitech Institute of Engineering and Technology',
    'United College of Engineering & Research',
    'University Polytechnic Diploma, Rama City, Kanpur',
    'Unnati Management College and Technology',
    'Urmila College of Technology and Management',
    'Uttar Pradesh Institute of Design and Research',
    'Veer Kunwar Institute of Technology',
    'Verangana Jhalkari Bai Government Girls Polytechnic, Jhansi',
    'Vidhya College of Engineering',
    'VIIT Polytechnic College, Sunhera, Bulandshahr',
    'Vijay Pratap Institute of Technology',
    'Vikas Institute of Engineering and Technology',
    'Vishvsaria Institute of Polytechnic',
    'Vision Institute of Technology',
    'Vivek College of Technical Education',
    'Vivekananda College of Polytechnic, Aligarh',
    'Vivekananda College of Technology & Management, Aligarh',
  ],
  'Dr. A. P. J. Abdul Kalam Technical University (AKTU), Lucknow': [
    'A.N.A. College of Engineering & Management, Bareilly',
    'ABES Engineering College, Ghaziabad',
    'ABES Institute of Technology, Ghaziabad',
    'ABSS Institute of Technology, Meerut',
    'Accurate Institute of Management & Technology, Gautam Buddh Nagar',
    'ACN College of Engineering & Management Studies, Aligarh',
    'Adhunik College of Engineering, Ghaziabad',
    'Ajay Kumar Garg Engineering College, Ghaziabad',
    'Aligarh College of Engineering & Technology, Aligarh',
    'Allenhouse Institute of Technology, Kanpur',
    'Amani Group of Institutions, Amroha',
    'Ambalika Institute of Management & Technology, Lucknow',
    'Apex Institute of Technology, Rampur',
    'Apollo Institute of Technology, Kanpur',
    'Ashoka Institute of Technology & Management, Varanasi',
    'Axis Institute of Technology & Management, Kanpur',
    'Azad Institute of Engineering & Technology, Lucknow',
    'B.B.S. College of Engineering and Technology, Allahabad',
    'B.N. College of Engineering & Technology (BNCET), Lucknow',
    'B.S.A. College of Engineering & Technology, Mathura',
    'Babu Banarasi Das Institute of Technology and Management, Lucknow',
    'Babu Banarasi Das Northern India Institute of Technology, Lucknow',
    'Babu Banarsi Das Institute of Technology, Ghaziabad',
    'Babu Sunder Singh Institute of Technology & Management, Lucknow',
    'Bansal Institute of Engineering & Technology, Lucknow',
    'Bhagwant Institute of Technology, Muzaffarnagar',
    'Bharat Institute of Technology, Meerut',
    'Bharat Ratna Baba Saheb Bhim Rao Ambedkar Rajkiya Engineering College, Pratapgarh',
    'Bharat Ratna Sardar Vallabhbhai Patel Rajkiya Engineering College, Basti',
    'Buddha Institute of Technology, Gorakhpur',
    'Bundelkhand Institute of Engineering & Technology, Jhansi',
    'Central Institute of Petrochemicals Engineering & Technology (CIPET), Lucknow',
    'Centre for Advance Studies, Lucknow',
    'Chaudhary Beeri Singh College of Engineering & Management, Agra',
    'College of Engineering & Rural Technology, Meerut',
    'Deewan V.S. Institute of Engineering & Technology, Meerut',
    'Delhi Institute of Engineering & Technology, Meerut',
    'Dev Bhoomi Group of Institutions, Saharanpur',
    'DNS College of Engineering & Technology, J.P. Nagar (Amroha)',
    'Dr. Ambedkar Institute of Technology for Divyangjan, Kanpur',
    'Dr. K.N. Modi Institute of Engineering & Technology, Ghaziabad',
    'Dr. M.C. Saxena College of Engineering & Technology, Lucknow',
    'Dr. Rizvi College of Engineering, Kaushambi',
    'Dr. Virendra Swarup Memorial Trust Group of Institutions, Unnao',
    'Dronacharya Group of Institutions, Gautam Buddh Nagar',
    'Eshan College of Engineering, Mathura',
    'Faculty of Engineering Shanti Niketan Trust\'s Group of Institutions, Meerut',
    'Faculty of Engineering, Agra College, Agra',
    'Feroze Gandhi Institute of Engineering and Technology, Raebareli',
    'FIT Engineering College, Meerut',
    'G.C.R.G. Memorial Trust\'s Group of Institutions, Faculty of Engineering, Lucknow',
    'G.L. Bajaj Group of Institutions, Mathura',
    'G.L. Bajaj Institute of Technology & Management, Gautam Buddh Nagar',
    'Galgotia\'s College of Engineering & Technology, Gautam Buddh Nagar',
    'Global Institute of Information Technology, Gautam Buddh Nagar',
    'Goel Institute of Technology & Management, Lucknow',
    'Gokaran Narvadeshwar Institute of Technology & Management, Barabanki',
    'Greater Noida College, Gautam Buddh Nagar',
    'Greater Noida Institute of Technology (Engineering Institute), Gautam Buddh Nagar',
    'Hardayal Technical Campus, Mathura',
    'Hi-Tech Institute of Engineering & Technology, Ghaziabad',
    'Himalayan Institute of Technology & Management, Lucknow',
    'Hindustan College of Science & Technology, Mathura',
    'HLM College, Ghaziabad',
    'HMFA Memorial Institute of Engineering & Technology, Allahabad',
    'I.E.C. College of Engineering & Technology, Gautam Buddh Nagar',
    'I.I.M.T. Engineering College, Meerut',
    'I.M.S. Engineering College, Ghaziabad',
    'I.T.S. Engineering College, Gautam Buddh Nagar',
    'Ideal Institute of Technology, Ghaziabad',
    'IIMT College of Engineering, Gautam Buddh Nagar',
    'Inderprastha Engineering College, Ghaziabad',
    'Indian Institute of Carpet Technology, Bhadohi',
    'Indian Institute of Handloom Technology, Varanasi',
    'Indraprastha Institute of Management & Technology, Saharanpur',
    'Institute of Engineering & Rural Technology, Allahabad',
    'Institute of Engineering & Technology, Lucknow',
    'Institute of Engineering & Technology, Sitapur',
    'Institute of Technology & Management, Aligarh',
    'Institute of Technology & Management, Gorakhpur',
    'Institute of Technology & Management, Lucknow',
    'Institute of Technology & Management, Maharajganj',
    'Isabella Thoburn College (Professional Studies), Lucknow',
    'J.P. Institute of Engineering & Technology, Meerut',
    'J.S.S. Academy of Technical Education, Gautam Buddh Nagar',
    'Jahangirabad Educational Trust\'s Group of Institutions, Faculty of Engineering, Barabanki',
    'JMS Group of Institutions, Ghaziabad',
    'JMS Institute of Technology, Ghaziabad',
    'Kalicharan Nigam Institute of Technology, Banda',
    'Kamla Nehru Institute of Physical & Social Sciences, Sultanpur',
    'Kamla Nehru Institute of Technology, Sultanpur',
    'Kanpur Institute of Technology, Kanpur',
    'Kashi Institute of Technology, Varanasi',
    'KCC Institute of Technology & Management, Gautam Buddh Nagar',
    'KCMT Campus 2 Prem Prakash Gupta Institute of Engineering, Bareilly',
    'KIET Group of Institutions, Ghaziabad',
    'KIPM College of Engineering & Technology, Gorakhpur',
    'KLS Institute of Engineering & Technology, Bijnor',
    'Kothiwal Institute of Technology & Professional Studies, Moradabad',
    'Krishna Institute of Technology, Kanpur',
    'Kunwar Satyavira College of Engineering and Management, Bijnor',
    'Landmark Technical Campus, J.P. Nagar (Amroha)',
    'LDC Institute of Technical Studies, Allahabad',
    'Lloyd Institute of Engineering and Technology, Gautam Buddh Nagar',
    'Lloyd Institute of Management & Technology, Gautam Buddh Nagar',
    'Lucknow Institute of Technology, Lucknow',
    'Maa Pateshwari Devi Rajkiya Engineering College, Gonda',
    'Madhu Vachaspati Institute of Engineering & Technology, Kaushambi',
    'Maharaja Agrasen College of Engineering & Technology, J.P. Nagar (Amroha)',
    'Maharana Institute of Professional Studies, Kanpur',
    'Maharana Institute of Technology & Sciences, Lucknow',
    'Maharana Pratap Engineering College, Kanpur',
    'Maharana Pratap Institute of Technology, Gorakhpur',
    'Mahatma Gandhi Mission College of Engineering & Technology, Gautam Buddh Nagar',
    'Mangalmay Institute of Engineering and Technology, Gautam Buddh Nagar',
    'Mangalmay Institute of Management and Technology, Gautam Buddh Nagar',
    'Marathwada Institute of Technology, Bulandshahr',
    'Maya Institute of Pharmacy, Hathras',
    'Meerut Institute of Engineering & Technology, Meerut',
    'Meerut Institute of Technology, Meerut',
    'Meerut International Institute of Technology, Meerut',
    'MG Institute of Management & Technology, Lucknow',
    'Modern College, Jhansi',
    'Modinagar Institute of Technology, Ghaziabad',
    'Moradabad Institute of Technology, Moradabad',
    'Naraina College of Engineering & Technology, Kanpur',
    'Neelam College of Engineering & Technology, Agra',
    'Neelkanth Institute of Technology, Meerut',
    'NIGC Institute of Technology and Management, Bijnor',
    'NITRA Technical Campus, Ghaziabad',
    'Noida Institute of Engineering & Technology, Gautam Buddh Nagar',
    'Panchwati Institute of Engineering & Technology, Meerut',
    'Prabhat Engineering College, Kanpur Dehat',
    'Pranveer Singh Institute of Technology, Kanpur',
    'Prasad Institute of Technology, Jaunpur',
    'Prayag Institute of Technology & Management, Allahabad',
    'R.D. Engineering College Research Centre, Ghaziabad',
    'R.D. Engineering College, Ghaziabad',
    'R.R. Institute of Modern Technology, Lucknow',
    'R.V. Institute of Technology, Bijnor',
    'Radha Govind Group of Institutions, Meerut',
    'Raj Kumar Goel Institute of Technology & Management, Ghaziabad',
    'Raj Kumar Goel Institute of Technology, Ghaziabad',
    'Raja Balwant Singh Engineering Technical Campus, Agra',
    'Rajarshi Rananjay Singh Institute of Management & Technology, Sultanpur',
    'Rajkiya Engineering College, Ambedkar Nagar',
    'Rajkiya Engineering College, Azamgarh',
    'Rajkiya Engineering College, Banda',
    'Rajkiya Engineering College, Bijnor',
    'Rajkiya Engineering College, Kannauj',
    'Rajkiya Engineering College, Mainpuri',
    'Rajkiya Engineering College, Sonbhadra',
    'Rajshree Institute of Management & Technology, Bareilly',
    'Rakshpal Bahadur College of Engineering & Technology, Bareilly',
    'Rameshwaram Institute of Technology & Management, Lucknow',
    'Rishi Institute of Engineering & Technology, Meerut',
    'S R Group of Institutions (College of Science and Engineering), Jhansi',
    'S.D. College of Engineering & Technology, Muzaffarnagar',
    'S.P. Memorial Institute of Technology, Kaushambi',
    'S.R. Institute of Management & Technology, Lucknow',
    'Sagar Institute of Technology & Management, Barabanki',
    'Samrat Ashok Rajkiya Engineering College, Mirzapur',
    'Sanskar College of Engineering & Technology, Ghaziabad',
    'Saraswati Higher Education & Technical College of Engineering, Varanasi',
    'Saroj Institute of Technology & Management, Lucknow',
    'School of Management Sciences, Lucknow',
    'Seth Vishambhar Nath Institute of Engineering & Technology, Barabanki',
    'Shambhu Nath Institute of Engineering & Technology, Allahabad',
    'Shanti Institute of Technology, Meerut',
    'Shivdan Singh Institute of Technology & Management, Aligarh',
    'Shri Nath Ji Institute for Technical Education, Meerut',
    'Shri Ram Swaroop Memorial College of Engineering & Management, Lucknow',
    'Shri Rammurti Smarak College of Engineering and Technology, Bareilly',
    'Shri Sidhi Vinayak Institute of Technology, Bareilly',
    'Shri Vishwanath College of Polytechnic, Sultanpur',
    'Sri Ram Group of Colleges, Muzaffarnagar',
    'Sri Rammurti Smarak College of Engineering Technology & Research, Bareilly',
    'SSLD Varshney Engineering College, Aligarh',
    'Sunderdeep Engineering College, Ghaziabad',
    'Sunrise Institute of Engineering Technical & Management, Unnao',
    'Suyash Institute of Information Technology, Gorakhpur',
    'SVS Group of Institutions, Meerut',
    'United College of Engineering & Research, Allahabad',
    'United College of Engineering & Research, Greater Noida (Gautam Buddh Nagar)',
    'United Institute of Technology, Allahabad',
    'Uttar Pradesh Textile Technology Institute, Kanpur',
    'Veer Kunwar Institute of Technology, Bijnor',
    'Vishveshwarya Group of Institutions, Gautam Buddh Nagar',
    'Vision Institute of Technology, Aligarh',
    'Vision Institute of Technology, Kanpur',
    'Vivekanand Institute of Technology & Science, Ghaziabad',
    'Vivekananda College of Technology & Management, Aligarh',
  ],
  'Jai Prakash University (JPU), Chapra': [
    'Acharya Drona Institute Teachers Training, Siwan',
    'AYT Teachers Training College, Guthani, Siwan',
    'B.D.S.M.M. College, Chapra',
    'B.S.B.R.A. Degree College, Barhariya, Siwan',
    'Baikunth Teachers Training College, Siwan',
    'Balmiki Singh Degree College, Thawe, Gopalganj',
    'Basudeo Singh Memorial B.Ed College, Mashrakh',
    'Bhola Prasad Singh College, Bhore',
    'D.A.V. PG College, Siwan',
    'D.B.S.D. Degree College, Kadna, Saran',
    'Damodar Rai Degree College, Nagra, Chapra',
    'Daroga Prasad Rai Degree College, Siwan',
    'Deshratna Rajendra Degree College, Ziradei',
    'Dr. B. P. Y. Degree College, Garkha, Saran',
    'Dr. B. Y. Degree College Kachnar, Chapra',
    'Dr. Mahachandra Prasad Singh College, Siwan',
    'Dr. P.N. Singh Degree College, Chapra',
    'Ganga Singh College, Chapra',
    'Gaura Kunwar Degree College, Aadampur, Siwan',
    'Gopeshwar College, Hathwa',
    'Gorakh Singh College, Maharajganj, Siwan',
    'Hari Ram College, Mairwa',
    'Hoti Lal Ramnath College, Amnour',
    'J.S. Bhardwaj Degree College, Jalalpur, Chapra',
    'Jagdam College, Chapra',
    'Jaglal Choudhary College, Chapra',
    'Jai Prakash Mahila College, Chapra',
    'Kamla Rai College, Gopalganj',
    'Lok Mahavidyalaya, Hafizpur, Saran',
    'M.R.D.C.R. Degree College, Mairwa, Siwan',
    'M.S.P. Degree College, Thawe, Gopalganj',
    'Maharani Punam Sahi B. Ed. College, Hathwa',
    'Mahendra Mahila College, Gopalganj',
    'Mathura Singh Teachers Training College, Jalalpur',
    'Mazharul Haq Degree College, Tarwara, Siwan',
    'Nand Lal Singh College, Daudpur',
    'Narayan College, Goriakothi',
    'PC Vigyan College, Chapra',
    'Pd. Devraj Mahavidyalaya, Kateya, Gopalganj',
    'Prabha Prakash Deg. College, Siwan',
    'Prabhunath College, Parsa',
    'Prakash B.Ed Teachers Training College, Chapra',
    'Pratik College of Education, Siwan',
    'Purvottar Railway College, Sonpur',
    'R.B.G.R. College, Maharajganj',
    'R.D.M. Degree College, Newaji Tola, Chapra',
    'Raja Singh College, Siwan',
    'Rajendra College, Chapra',
    'Rajendra Kishori B.Ed College, Sughari, Siwan',
    'Ram Jaipal College, Chapra',
    'Ramadhar Singh Teachers Training College, Ekma',
    'S. R. Teachers Training College, Mirganj',
    'S.M.D Degree College, Jalalpur',
    'Shyam Sai Institute of Education, Mairwa, Siwan',
    'Solanki B.Ed Teachers Training College, Chapra',
    'Sri Kant Babu Degree College, Gopalganj',
    'Subhwanti Institute of Education, Siwan',
    'Vidya Bhawan Mahila College, Siwan',
    'Yadu Nandan College, Dighwara',
    'Z.A. Islamia College, Siwan',
  ],
  'Jharkhand University of Technology (JUT), Ranchi': [
    'Al-Kabir Polytechnic Jamshedpur, East Singhbhum',
    'B.A College of Engineering & Technology Jamshedpur, East Singhbhum',
    'Beharagora Polytechnic, East Singhbhum',
    'Birsa Institute of Technology Sindri, Dhanbad',
    'BITT Polytechnic Ranchi, Ranchi',
    'Cambridge Institute of Polytechnic Ranchi, Ranchi',
    'Cambridge Institute of Technology Tatisilwai Ranchi, Ranchi',
    'Centre for Bioinformatics Ranchi, Ranchi',
    'Chaibasa Engineering College, West Singhbhum',
    'Chandil Polytechnic, Saraikela-Kharsawan',
    'D.A.V Institute of Engineering & Technology Palamu, Palamu',
    'Dhanbad Institute of Technology Dhanbad, Dhanbad',
    'Dumka Engineering College, Dumka',
    'Garhwa Polytechnic, Garhwa',
    'Girija Institute of Polytechnic Ramgarh, Ramgarh',
    'Gola Polytechnic, Ramgarh',
    'Government Engineering College Palamu, Palamu',
    'Government Polytechnic Adityapur, Saraikela-Kharsawan',
    'Government Polytechnic Bhaga, Dhanbad',
    'Government Polytechnic Dhanbad, Dhanbad',
    'Government Polytechnic Dumka, Dumka',
    'Government Polytechnic Jagannathpur, West Singhbhum',
    'Government Polytechnic Kharsawan, Saraikela-Kharsawan',
    'Government Polytechnic Khutri, Bokaro, Bokaro',
    'Government Polytechnic Koderma, Koderma',
    'Government Polytechnic Latehar, Latehar',
    'Government Polytechnic Nirsa, Dhanbad',
    'Government Polytechnic Ranchi, Ranchi',
    'Government Polytechnic Sahibganj, Sahibganj',
    'Government Polytechnic Simdega, Simdega',
    'Government Women’s Polytechnic Bokaro, Bokaro',
    'Government Women’s Polytechnic Dumka, Dumka',
    'Government Women’s Polytechnic Jamshedpur, East Singhbhum',
    'Government Women’s Polytechnic Ranchi, Ranchi',
    'Gumla Polytechnic, Gumla',
    'Guru Govind Singh Educational Society Technical Campus Bokaro, Bokaro',
    'Institute of Science and Management Pundag Ranchi, Ranchi',
    'K.K. College of Engineering & Management Dhanbad, Dhanbad',
    'K.K. Polytechnic Dhanbad, Dhanbad',
    'Khandoli Institute of Technology Giridih, Giridih',
    'Madhupur Polytechnic, Deoghar',
    'Maryland Institute of Technology & Management Jamshedpur, East Singhbhum',
    'National Institute of Foundry and Forge Technology Hatia, Ranchi',
    'Nilai Education Trust\'s Group of Institutions Ranchi, Ranchi',
    'Nilai Educational Trust\'s Group of Institutions Ranchi, Ranchi',
    'Pakur Polytechnic, Pakur',
    'Pemiya Rishikesh Institute of Technology Dhanbad, Dhanbad',
    'R.T.C Institute of Technology Ranchi, Ranchi',
    'R.V.S College of Engineering & Technology Jamshedpur, East Singhbhum',
    'Ramgarh Engineering College, Ramgarh',
    'Ramgovind Institute of Technology Koderma, Koderma',
    'Ramgovind Polytechnic Institute Koderma, Koderma',
    'RTC Institute of Technology Ranchi, Ranchi',
    'Sarojini Institute of Technology Bundu, Ranchi',
    'Silli Polytechnic, Ranchi',
    'Subhash Institute of Technology Giridih, Giridih',
    'Vidya Memorial Institute of Technology Ranchi, Ranchi',
    'Xavier Institute of Polytechnic and Technology Ranchi, Ranchi',
  ],
  'Lalit Narayan Mithila University (LNMU), Darbhanga': [
    'A. N. D. College, Shahpur Patory, Samastipur',
    'A. P. S. M. College, Barauni, Begusarai',
    'A.H.S.A. College, Madhubani',
    'A.M.M. College, Benipur, Darbhanga',
    'B. M. A. College, Baheri, Darbhanga',
    'B. M. College, Rahika, Madhubani',
    'B. R. B. College, Samastipur',
    'Baba Vishwanath Kedarnath Vimala College, Rampur Dudhpura, Samastipur',
    'Bahera College, Bahera, Darbhanga',
    'Basudev Ram Kishor Choudhary College, Jitwarpur Kumhira, Mushrigharari, Samastipur',
    'Bhardwaj College, Sakarpura, Hasanpur Road, Samastipur',
    'C. M. B. College, Deorh, Ghoghardiha, Madhubani',
    'C. M. College, Darbhanga',
    'C. M. J. College, Downwarihat, Madhubani',
    'C. M. Law College, Darbhanga',
    'C. M. Science College, Darbhanga',
    'Chhattu Roy College, Kishanpur, Samastipur',
    'D. B. College, Jaynagar, Madhubani',
    'D. B. K. N. College, Narhan, Samastipur',
    'D.N.Y. College, Madhubani',
    'Dr. L. K. V. D. College, Tajpur, Samastipur',
    'G. D. College, Begusarai',
    'G. M. R. D. College, Mohanpur, Samastipur',
    'H. P. S. College, Madhepur, Madhubani',
    'Hari Anand College, Akaur, Benipatti, Madhubani',
    'J. K. College, Biraul, Darbhanga',
    'J. M. D. P. L. Mahila College, Madhubani',
    'J. N. College, Madhubani',
    'J. N. College, Nehra, Darbhanga',
    'Janaki Devi Gaurishankar Saraf Degree Mahila College, Jaynagar, Madhubani',
    'Janta Degree College, Korthu, Darbhanga',
    'K. S. College, Laheriasarai, Darbhanga',
    'K. V. Sc. College, Ucchaith, Madhubani',
    'K.S.R. College, Sarairanjan, Samastipur',
    'L. N. J. College, Jhanjharupr, Madhubani',
    'L.C.S. College, Darbhanga',
    'Lutan Jha College, Nanaur, Madhubani',
    'M. K. College, Laheriasarai, Darbhanga',
    'M. K. S. College, Trimuhan Chandauna, Darbhanga',
    'M. L. S. College, Sarisabpahi, Madhubani',
    'M. L. S. M. College, Darbhanga',
    'M. R. M. College, Darbhanga',
    'M.G. College, Darbhanga',
    'M.M. College, Kadirabad, Darbhanga',
    'M.M.T.M. College, Darbhanga',
    'M.R.S.M. College, Anandpur, Darbhanga',
    'Mahanth Narayan Das College, Chandauli, Ujiyarpur (Samastipur)',
    'Mahanth Ram Jiwan Das College, Vishnupur, Begusarai',
    'Marwari College, Darbhanga',
    'Millat College, Laheriasarai, Darbhanga',
    'N. Jha Mahila College, Laheriasarai, Darbhanga',
    'P.L.M. College, Jhanjharpur, Madhubani',
    'Prof. Chandra Shekhar Jha P.D.K.J. College, Andharatharhi, Madhubani',
    'Q.A. Degree College, Jale, Darbhanga',
    'R. B. College, Dalsinghsarai, Samastipur',
    'R. B. S. College, Andaur, Samastipur',
    'R. C. S. College, Manjhaul, Begusarai',
    'R. K. College, Madhubani',
    'R. N. A. R. College, Samastipur',
    'R. N. College, Pandaul, Madhubani',
    'R.B.J. College, Bela, Darbhanga',
    'R.B.S. College, Teyai, Begusarai',
    'R.C.S.S. College, Bihat, Begusarai',
    'R.K. Mishra College, Chandauna, Darbhanga',
    'R.K.A. Law College, Begusarai',
    'R.L.S.R.M.D. College, Shivajinagar, Samastipur',
    'R.N.J.D. College, Madhwarpur, Madhubani',
    'Rajmata Dr. Sangeeta Roy Degree College, Barki Rajwa, Hasanpur, Samastipur',
    'S. B. S. S. College, Begusarai',
    'S. K. M. College, Begusarai',
    'S.K. College, Thatiya, Rosera, Samastipur',
    'S.M.J. College, Khajedih, Madhubani',
    'S.M.R.C.K. College, Samastipur',
    'S.N.M. College, Bhairaw Sthan, Madhubani',
    'Samastipur College, Samastipur',
    'Sant Kabir College, Samastipur',
    'Sati-Bharat College, Parari, Darbhanga',
    'Subdivision Govt. Degree College, Benipur, Darbhanga',
    'U. P. College, Pusa, Samastipur',
    'U. R. College, Rosera, Samastipur',
    'V. S. J. College, Rajnagar, Madhubani',
    'Vidhi Mahavidyalay, Samastipur',
    'Vidya Sagar Thakur G.K.P.D. College, Karpoorigram, Samastipur',
    'Women’s College, Samastipur',
  ],
  'Magadh University (MU), Bodh Gaya': [
    'A. M. College, Gaya',
    'A. N. S. College, Nabinagar, Aurangabad',
    'Adhikari College, Silar, Aurangabad',
    'Anugrah Memorial Law College, Gaya',
    'Anugrah Smarak College, Jehanabad',
    'B. B. M. College, Okri, Jehanabad',
    'B. N. S. College, Sobh, Barachatti, Gaya',
    'Bhuneshwar Prasad Yadav College, Gaya',
    'C. S. Janta College, Chakand, Gaya',
    'Dashrath Prasad Ramnandan Pandey B.Ed. College, Aurangabad',
    'Daudnagar College, Daudnagar, Aurangabad',
    'Dr. Ram Narayan Prasad College, Arwal',
    'Dr. Vijay Kumar Singh College, Rafiganj, Aurangabad',
    'Dr. Zakir Hussain Evening College, Sherghati, Gaya',
    'Fatehpur Sanda College, Arwal',
    'G. B. M. College, Gaya',
    'Gautam Buddha College, Belaganj, Gaya',
    'Gaya College, Gaya',
    'Guro Binda College, Nawada',
    'J. J. College, Gaya',
    'Jang Bahadur Singh Memorial College, Aurangabad',
    'Janta College, Labhari, Aurangabad',
    'Jehanabad College, Jehanabad',
    'K. L. S. College, Nawada',
    'K. S. M. College, Aurangabad',
    'K. S. Y. College, Barun, Aurangabad',
    'Kamta Prasad Sharma College, Hulasganj, Jehanabad',
    'Kamta Prasad Singh College, Gaya',
    'Kishori Sinha Mahila College, Aurangabad',
    'Krishak College, Dewdha, Pakribarwan, Nawada',
    'Lalan Prasad Yadav College, Gaya',
    'Laldhari Memorial College, Gaya',
    'Laloo Mandal College, Gaya',
    'Laxmi Narayan College, Tankuppa, Gaya',
    'Lila Mandal College of A. H. Education, Tankuppa, Gaya',
    'M. S. Y. College, Gaya',
    'Maa Bageshwari College, Gaya',
    'Maa Kamla Chandrika Babu Mahila Mahavidyalaya, Jehanabad',
    'Maa Kamla Chandrika Jee Vidyapeeth, Hulasganj, Jehanabad',
    'Mahabodhi College, Belaganj, Gaya',
    'Maharana Pratap College, Dev, Aurangabad',
    'Mahavir College, Gaya',
    'Mahila College, Daudnagar, Aurangabad',
    'Mahila College, Tekari, Gaya',
    'Mahila College, Warisaliganj, Nawada',
    'Mirza Ghalib College, Gaya',
    'Nadariganj College, Nadariganj, Nawada',
    'Nawada Law College, Nawada',
    'Prof. Vijay Shankar Rai Mahila College, Sherghati, Gaya',
    'R. C. S. College, Kurtha, Arwal',
    'R. L. S. Y. College, Aurangabad',
    'R. L. S. Y. College, Gaya',
    'R. M. W. College, Nawada',
    'Rajdeo Ramchandra College, Banahi Fhesar, Aurangabad',
    'Ram Lakhan Singh Yadav College, Jehanabad',
    'Ramrati Sundarshila College, Aurangabad',
    'Ramsharan Yadav College, Deokund, Aurangabad',
    'Ravi Kant Poonam College, Nawada',
    'S. A. College, Nawada',
    'S. B. A. N. College, Darheta Lari, Aurangabad',
    'S. D. College, Kaler, Aurangabad',
    'S. D. College, Paraiya, Gaya',
    'S. K. M. College, Nawada',
    'S. M. College, Bodhgaya, Gaya',
    'S. M. S. G. College, Sherghati, Gaya',
    'S. N. S. College, Tekari, Ga',
    'S. N. Sinha College, Jehanabad',
    'S. N. Sinha College, Warsaliganj, Nawada',
    'S. P. Y. College, Gaya',
    'S. R. S. College, Nawada',
    'S. S. College, Jehanabad',
    'S. Sinha College, Aurangabad',
    'Sanjay Gandhi Mahila College, Bairagi, Gaya',
    'Sanjay Singh Yadav College, Gaya',
    'Sanjay Singh Yadav College, Rafiganj, Aurangabad',
    'Saptrishi College, Nawada',
    'Shaheed Jagdev Smarak College, Kurtha, Arwal',
    'Sri Krishna Mahila College, Jehanabad',
    'Surendra Prasad Yadav Law College, Gaya',
    'Suresh Radhika College, Maya Bigha, Kadirganj, Nawada',
    'T. S. College, Hisua, Nawada',
    'Thakur B. D. Sinha Jangta College, Goh, Aurangabad',
    'Wazirganj College, Wazirganj, Gaya',
  ],
  'Munger University (MU), Munger': [
    'B R M College, Munger',
    'B. N. M. College, Barhiya, Lakhisarai',
    'Bishwanath Singh Institute of Legal Studies, Munger',
    'C N B College Hathiama, Sheikhpura',
    'D.S.M. College, Jhajha, Jamui',
    'Dhanraj Singh College Sikandra, Jamui',
    'Dr. Arvind Kumar College, Bishanpur, Jamui',
    'H.S. College, Haveli Kharagpur, Munger',
    'International College Ghosaith, Lakhisarai',
    'J. R. S. College, Jamalpur, Munger',
    'J.M.S. College, Munger',
    'Jamalpur College, Jamalpur, Munger',
    'K K M College, Jamui',
    'K S S College, Lakhisarai',
    'K. D. S College, Gogri, Khagaria',
    'K.M.D. College, Parbatta, Khagaria',
    'Koshi College, Khagaria',
    'M S College Alouli, Sonihar, Khagaria',
    'Mahila College, Khagaria',
    'Mahila Mahavidyalaya Barhiya, Lakhisarai',
    'P P Yadav College Chakai, Jamui',
    'R Lal College, Lakhisarai',
    'R.D College, Sheikhpura',
    'R.D. & D.J. College, Munger',
    'R.S. College, Tarapur, Munger',
    'Ramdhani Bhagat Degree College, Sangrampur, Munger',
    'S A Eklavya Degree College, Jamui',
    'S B N College Garhi Rampur, Munger',
    'S K College Lohanda, Jamui',
    'S S College, Mehus, Sheikhpura',
    'S. K. R. College, Barbigha, Sheikhpura',
    'Sanjay Gandhi Mahila College, Sheikhpura',
    'Shyama Prasad Mahila College, Jamui',
    'Smt. Ganga Devi Memorial College, Sudamapur, Jamui',
  ],
  'Patliputra University (PPU), Patna': [
    'A. N. College, Patna',
    'Allama Iqbal College, Biharsharif, Nalanda',
    'ANS College, Barh',
    'Awadhesh Prasad Mahavidyalaya, Patna',
    'B. B. M. B. G. Kanya College, Patna',
    'B. D. College, Patna',
    'B. L. P. College, Masaurhi, Patna',
    'B. R. Degree College, Nalanda',
    'B. S. College, Danapur',
    'Bansropan Ram Bahadur Singh Yadav College, Kanhauli, Patna',
    'Chandradeo Prasad Verma College, Simri, Patna',
    'College of Commerce, Arts & Science, Patna',
    'D. N. College, Masaurhi, Patna',
    'Deo Sharan Women\'s Evening College, Sohsarai, Nalanda',
    'Dr. C. P. Thakur College, Naubatpur, Patna',
    'Dr. Ram Raj Singh Mahila Mahavidyalaya, Chandi, Nalanda',
    'G. D. M. College, Harnaut, Nalanda',
    'G. J. College, Rambagh, Bihta',
    'Ganga Devi Mahila Mahavidyalaya, Patna',
    'Govt. Degree College, Rajgir, Nalanda',
    'Govt. Women\'s College, Gardanibagh, Patna',
    'J. D. Women\'s College, Patna',
    'J. P. Snatak Mahavidyalaya, Biyabani, Biharsharif, Nalanda',
    'Jagat Narayan Lal College, Khagaul, Patna',
    'Jyoti Kunwar College, Fatehpur, Patna',
    'K. S. T. College, Sohsarai, Nalanda',
    'Kameshwar Prasad Singh College, Nadwan, Patna',
    'Kisan College, Nalanda',
    'L. P. Shahi College, Patna',
    'L. S. T. Gramin Mahavidyalaya, Aungaridham, Nalanda',
    'M. M. College, Bikram, Patna',
    'Magadh Mahavidyalaya, Chandi, Nalanda',
    'Mahabodhi Mahavidyalaya, Nalanda',
    'Mahatma Budh Hiraman College, Nalanda',
    'Mahila College, Khagaul, Patna',
    'Malti Dhari College, Naubatpur, Patna',
    'Mata Ashapuri Mahavidyalaya, Nalanda',
    'Nalanda College, Biharsharif, Nalanda',
    'Nalanda Mahila College, Biharsharif, Nalanda',
    'Nalanda Sodh Sansthan, Nalanda',
    'Nunwati Jagdev Singh College, Bakhtiyarpur, Patna',
    'Oriental College, Patna City',
    'P. L. S. College, Masaurhi, Patna',
    'P. M. S. College, Paharpura, Nalanda',
    'P. N. K. College, Achhua, Patna',
    'Patna Muslim Science College, Patna',
    'R. L. S. Y. College, Anishabad, Patna',
    'R. L. S. Y. College, Bakhtiarpur, Patna',
    'R. L. S. Y. College, Nalanda',
    'R. Lal College, Nalanda',
    'R. P. College, Datiyana, Bikram, Patna',
    'R. P. M. College, Patna City',
    'R. P. S. College, Bailey Road, Patna',
    'R. P. S. College, Harnaut, Nalanda',
    'R. P. S. Mahila College, Bailey Road, Patna',
    'Rajkiya Mahila Mahavidyalaya, Gulzarbagh, Patna',
    'Ram Krishna Dwarika College, Patna',
    'Ram Ratan Singh College, Mokama, Patna',
    'Ram Roop Prasad College, Patna',
    'S. K. M. V. College, Fatuha, Patna',
    'S. M. D. College, Punpun, Patna',
    'S. N. A. Evening College, Barh, Patna',
    'S. P. College, Hilsa, Nalanda',
    'S. P. M. College, Udantpuri, Nalanda',
    'S. P. Verma College, Rajakuan, Biharsharif, Nalanda',
    'S. U. College, Hilsa, Nalanda',
    'Sant Sandhya Das Mahila College, Barh, Patna',
    'Sir Ganesh Dutt Memorial College, Patna',
    'Snatak College, Nalanda',
    'Sogara College, Biharsharif, Nalanda',
    'Sri Arvind Mahila College, Patna',
    'Sri Bhuwaneshwari Raja College, Barh, Patna',
    'Sri Guru Gobind Singh College, Patna Saheb',
    'Sri Ram Narayan College, Barh, Patna',
    'T. P. S. College, Patna',
    'Trimurti College, Ismailpur, Patna',
    'Vardhman Mahavir College, Pawapuri, Nalanda',
  ],
  'Patna University (PU), Patna': [
    'B. N. College, Patna',
    'College of Arts & Crafts, Patna',
    'Magadh Mahila College, Patna',
    'Patna College, Patna',
    'Patna Law College, Patna',
    'Patna Science College, Patna',
    'Patna Training College, Patna',
    'Patna Women\'s College, Patna',
    'Patna Women\'s Training College, Patna',
    'Vanijya Mahavidyalaya, Patna',
  ],
  'Purnea University (PU), Purnea': [
    'A.J.M. COLLEGE, BANMANKHI, PURNIA',
    'AL SHAMS MILLIA COLLEGE, ARARIA',
    'ALHAJ NAIMUDDIN SHAHIDI COLLEGE, NISTA, KATIHAR',
    'ARARIA COLLEGE, ARARIA',
    'B.D. COLLEGE, BARSOI, KATIHAR',
    'B.M. COLLEGE, BARARI, KATIHAR',
    'B.N.C. COLLEGE, DHAMDAHA, PURNIA',
    'BALRAMPUR DEGREE COLLEGE, BALRAMPUR, KATIHAR',
    'D.S. COLLEGE, KATIHAR',
    'FORBESGANJ COLLEGE, FORBESGANJ, ARARIA',
    'G.L.M. COLLEGE, BANMANKHI, PURNEA',
    'GOVT DEGREE COLLEGE, BAISI, PURNEA',
    'GOVT DEGREE COLLEGE, DHAMDA, PURNEA',
    'INSAN DEGREE COLLEGE, SHIKSHA NAGAR, KISHANGANJ',
    'J.D.S.S. MAHILA COLLEGE, FORBESGANJ, ARARIA',
    'K N DEGREE COLLEGE, BAKHARI, KURSHAKANTA, ARARIA',
    'K.D. COLLEGE, RANIGANJ, ARARIA',
    'KB JHA COLLEGE, KATIHAR',
    'LUV KUSH DEGREE COLLEGE, PRANPUR, KATIHAR',
    'M.H.A.N.D. COLLEGE, THAKURGANJ, KISHANGANJ',
    'M.L. ARYA COLLEGE KASBA, PURNEA',
    'M.L.D.P.K.Y. COLLEGE, ARARIA',
    'MAHATMA GANDHI MEMORIAL DEGREE COLLEGE, POTHIA, KISHANGANJ',
    'MARWARI COLLEGE, KISHANGANJ',
    'MJ.M. MAHILA COLLEGE, KATIHAR',
    'N.D. COLLEGE, RAMBAGH, PURNIA',
    'NEHRU COLLEGE, BAHADURGANJ, KISHANGANJ',
    'P.S.D COLLEGE, HARDA, PURNIA',
    'PEOPLES COLLEGE, ARARIA',
    'PURNEA COLLEGE, PURNEA',
    'PURNEA MAHILA MAHAVIDYALYA, PURNEA',
    'R.K.K. COLLEGE, PURNIA',
    'R.K.S. MAHILA COLLEGE, KISHANGANJ',
    'R.L. COLLEGE, MADHAVNAGAR, PURNEA',
    'R.Y. MANIHARI COLLEGE, MANIHARI, KATIHAR',
    'RDS COLLEGE, SALMARI, KATIHAR',
    'S.N.S.Y. DEGREE COLLEGE, RAMBAGH, PURNIA',
    'S.R.C DEGREE COLLEGE, KATIHAR',
    'SCHOLARS DEGREE COLLEGE B. KOTHI, PURNIA',
    'SEEMANCHAL DEGREE COLLEGE, KATIHAR',
    'SUNRISE POONAM VIRENDRA DEGREE COLLEGE OF EDUCATION, PURNEA',
    'Y.N.P. DEGREE COLLEGE, RANIGANJ, ARARIA',
  ],
  'State Board of Technical Education (SBTE), Bihar': [
    'Akash Polytechnic College, Gaya',
    'Amrath Technical College, Gaya',
    'Arjun College of Technical Education, Naugachia, Bhagalpur',
    'Aryabhatt Polytechnic, Gaya',
    'Aryaman Higher Education, Nagarnausa, Nalanda',
    'Awadhesh Sharma Institute of Technology, Naubatpur, Patna',
    'Azmet College of Engineering and Technology, Kishanganj',
    'Azmet Institute of Technology, Kishanganj (2nd Shift)',
    'Baba Heera Singh Deepa Singh Jee College of Higher Education, Piro, Bhojpur',
    'Baddiuzama Khan Polytechnic Institute, Sitamarhi',
    'Braj Kishor Narayan Singh Government Polytechnic, Gopalganj',
    'Buddha Institute of Technology, Gaya',
    'Buddha Institute of Technology, Gaya (2nd Shift)',
    'Buddha Polytechnic Institute, Gaya',
    'Buddha Polytechnic Institute, Gaya (2nd Shift)',
    'Buddha Polytechnic, Lalganj, Vaishali',
    'C. R. K. Polytechnic, Hajipur, Vaishali',
    'Champaran College of Professional Education, East Champaran',
    'Champaran College, Bagha, West Champaran',
    'Champaran Group of Institutions, West Champaran',
    'Chanakya Institute of Polytechnic and Technology, Koilwar, Bhojpur',
    'Damyanti Devi Polytechnic College, Dobhi, Gaya',
    'Divine Institute of Technology, Siwan',
    'Dr. Ashok Gagan College, Bihta, Patna',
    'Ekalavya Institute of Higher Education, Madhepura',
    'Exalt College of Polytechnic, Vaishali',
    'Ganga Memorial College of Polytechnic, Harnaut, Nalanda',
    'GEMS Polytechnic College, Aurangabad',
    'Girija Devi Polytechnic College, Bihiya, Bhojpur',
    'Government Polytechnic, Araria',
    'Government Polytechnic, Arwal',
    'Government Polytechnic, Aurangabad',
    'Government Polytechnic, Banka',
    'Government Polytechnic, Barh, Patna',
    'Government Polytechnic, Begusarai (Barauni)',
    'Government Polytechnic, Bhagalpur',
    'Government Polytechnic, Bhojpur (Jagdishpur)',
    'Government Polytechnic, Buxar',
    'Government Polytechnic, Darbhanga',
    'Government Polytechnic, East Champaran (Motihari)',
    'Government Polytechnic, Gaya',
    'Government Polytechnic, Gopalganj',
    'Government Polytechnic, Jamui',
    'Government Polytechnic, Jehanabad',
    'Government Polytechnic, Kaimur (Bhabua)',
    'Government Polytechnic, Katihar',
    'Government Polytechnic, Khagaria',
    'Government Polytechnic, Kishanganj',
    'Government Polytechnic, Lakhisarai',
    'Government Polytechnic, Madhepura',
    'Government Polytechnic, Madhubani',
    'Government Polytechnic, Munger',
    'Government Polytechnic, Muzaffarpur',
    'Government Polytechnic, Nalanda (Asthawan)',
    'Government Polytechnic, Nawada',
    'Government Polytechnic, Patna (Gulzarbagh)',
    'Government Polytechnic, Purnea',
    'Government Polytechnic, Rohtas (Dehri-on-Sone)',
    'Government Polytechnic, Saharsa',
    'Government Polytechnic, Saran (Chapra)',
    'Government Polytechnic, Sheikhpura',
    'Government Polytechnic, Sheohar',
    'Government Polytechnic, Sitamarhi',
    'Government Polytechnic, Siwan',
    'Government Polytechnic, Supaul (Raghopur)',
    'Government Polytechnic, Tekari, Gaya',
    'Government Polytechnic, Vaishali',
    'Government Polytechnic, West Champaran (Bettiah)',
    'Government Textile Technology, Bhagalpur',
    'Government Women\'s Polytechnic, Muzaffarpur',
    'Government Women\'s Polytechnic, Patna',
    'Gurudeo College of Technology and Management, Hajipur, Vaishali',
    'Gyansarover Institute of Management and Technology, Arap, Patna',
    'Hi Tech Polytechnic College, Bettiah, West Champaran',
    'Himalaya Institute of Technology, Ebrahimpur, Awadhara, Patna',
    'J. P. Institute of Technology, Biharsharif, Nalanda',
    'Jamui Institute of Technology, Jamui',
    'Jamui Polytechnic, Jamui',
    'K. K. College of Engineering & Management, Nalanda (2nd Shift)',
    'K. K. Polytechnic, Nalanda',
    'K. K. Polytechnic, Nalanda (2nd Shift)',
    'Kameshwar Narayan Singh Government Polytechnic, Samastipur',
    'Kanhaiya Memorial College of Higher Education, Gaya',
    'Kinesis Institute of Technology, Masaurhi, Patna',
    'Krishna Institute of Technology, Singhia Khurd, Samastipur',
    'Kusumraj Educational Institution, Bikram, Patna',
    'Lichavi Institute of Professional Studies, Muzaffarpur',
    'Maa Kamakhya Polytechnic, Ramdihra, Rohtas',
    'Maa Kanti College of Higher Education, Fatwah, Patna',
    'Maalik Institute of Technology, Gaya',
    'Magadh Institute of Technology, Nasriganj, Patna',
    'Maharana Pratap Institute of Technology, Buxar',
    'Mamta Institute of Education, Siwan',
    'Maulana Azad College of Engineering & Technology, Neora, Patna',
    'Millia Institute of Technology, Rambagh, Purnea',
    'Millia Polytechnic, Purnea',
    'Millia Polytechnic, Veriadangi, Kishanganj',
    'Mona Polytechnic College, Beldarichak, Patna',
    'Mothers Institute of Technology, Bihta, Patna',
    'MPS Polytechnic College, Muzaffarpur',
    'Muzaffarpur College of Professional Education, Muzaffarpur',
    'Netaji Subhas Institute of Polytechnic, Bihta, Patna',
    'Netaji Subhash Institute of Technology, Bihta, Patna',
    'New Government Polytechnic, Patna (Patliputra Colony)',
    'Nexus Institute of Technology, West Champaran',
    'Patliputra Institute of Management and Technology, Danapur, Patna',
    'Patna Sahib Technical Campus, Vaishali',
    'Patna Sahib Technical Campus, Vaishali (2nd Shift)',
    'Prabhu Kailash Polytechnic, Aurangabad',
    'R. L. Polytechnic College, Hilsa, Nalanda',
    'R. P. Sharma Institute of Technology, Danapur, Patna',
    'Rajeev College of Professional Education, Sitamarhi',
    'Ram Pratap Institute of Higher Education, Sherghati, Gaya',
    'Ram Sharan Roy College of Technology, Mahnar, Vaishali',
    'RDS Institute of Technology, Bodhgaya, Gaya',
    'Rimu Institute of Technology, Pant Nagar, Gaya',
    'Rungta Institute of Technology and Management, Forbesganj, Araria',
    'Satyam Institute of Technology, Gaurichak, Patna',
    'Satyam International Institute of Technology, Gaurichak, Patna',
    'Shanti Niketan Institute of Technology, Chakand, Gaya',
    'Shri Ram Polytechnic, Madhubani',
    'Sir BD Singh Institute of Technology, Gaurichak, Patna',
    'Sityog Institute of Polytechnic, Aurangabad',
    'Sityog Institute of Technology, Aurangabad',
    'SNS Vidyapeeth, Motihari, East Champaran',
    'Subhash Institute of Technology, Jamui',
    'Sunaina Polytechnic College, Lakhisarai',
    'Vidya Education Group, Masaurhi, Patna',
    'Vivekanand Institute of Technology, Naubatpur, Patna',
  ],
  'Tilka Manjhi Bhagalpur University (TMBU), Bhagalpur': [
    'A.K. Gopalan College, Sultanganj, Bhagalpur',
    'Adityanath Memorial College, Bounsi, Banka',
    'B. L. Sarraf Commerce College, Naugachia, Bhagalpur',
    'Bhagalpur National College, Bhagalpur',
    'C.M. College, Bounsi, Banka',
    'D.N. Singh College, Bhusia, Rajaun, Banka',
    'G. B. College, Naugachia, Bhagalpur',
    'Jay Prakash College, Narayanpur, Bhagalpur',
    'L.N.B.J. Mahila College, Bhramarpur, Bhagalpur',
    'Madan Ahilya Mahila College, Naugachia, Bhagalpur',
    'Mahadeo Singh College, Bhagalpur',
    'Marwari College, Bhagalpur',
    'Mathurapur Mahavidyalaya, Mathurapur, Bhagalpur',
    'Murarka College, Sultanganj, Bhagalpur',
    'Muslim Minority College, Bhagalpur',
    'P. B. S. College, Banka',
    'P.N.A. Science Mahavidyalaya, Bhagalpur',
    'R.R.B. College, Karharia, Bhagalpur',
    'S. S. V. College, Kahalgaon, Bhagalpur',
    'S.D.M.Y. College, Dhoraiya, Banka',
    'S.S.P.S. College, Shambhuganj, Banka',
    'Sabour College, Sabour, Bhagalpur',
    'Sarvajanik College, Sarvodaynagar, Banka',
    'Satyadeo Mahavidyalaya, Gauripur, Bihpur, Bhagalpur',
    'Sharda Jhunjhunwala Mahila College, Bhagalpur',
    'Sunderwati Mahila College, Bhagalpur',
    'T.N.B. College, Bhagalpur',
    'T.N.B. Law College, Bhagalpur',
    'Tarar College, Tarar, Ghogha, Bhagalpur',
  ],
  'Veer Kunwar Singh University (VKSU), Ara': [
    'Al-Hafeez College, Ara',
    'Anjabit Singh College, Bikramganj, Rohtas',
    'Awadhoot Bhagwan Ram College, Sasaram',
    'B. Ed. College, Parsathua',
    'B.G. College, Ramlal Nagar, Bhabhua, Kaimur',
    'B.K.S. College, Kuddi, Chand, Kaimur',
    'B.N. College, Indour, Sasaram, Rohtas',
    'B.P.J.P.S. Mahila College, Rajpur',
    'B.S. College, Hata, Chenari, Rohtas',
    'B.S.S. College, Bachari, Piro',
    'Baba Ganinath College, Dehri-On-Sone, Jamuhar, Sasaram',
    'Bindeshwari Dubey Mahavidyalya, Bihiya Kataiya, Bhojpur',
    'Chanakya Academy Mahila Mahavidyalaya, Sarenja, Rajpur, Buxar',
    'Chaudhary Charan Singh College, Rajpur, Rohtas',
    'Chaudhary Charan Singh Evening College, Bhagirtha-Narwar, Kochas, Rohtas',
    'D. D. College, Dhanupra, Ara Bhojpur',
    'D.K. College, Dumraon',
    'D.K.M. College, Dumari, Buxar',
    'D.S.S.V. College, Simri, Buxar',
    'Dharikshan Shanti Meera Sidhnath Degree Mahavidyalaya, Kulhariya, Bhojpur',
    'Dr. Arvind Teachers Training College, Dularpur',
    'Dr. K. K. Mandal College, Jagdishpur, Bhojpur',
    'Dr. K.K. Mandal Mahila College, Buxar',
    'Durgawati Mahavidyalaya, Bichhiya, Dumari, Kaimur',
    'G.B. College, Ramgarh',
    'Geeta Pradeep College of Higher Education, Asani, Bhojpur',
    'Girish Narayan Mishra College, Parsathua, Rohtas',
    'Gram Bharti Balika Vidyapeeth, Ramgarh, Kaimur',
    'Guru Prakash College, Kekadha, Kilani, Kaimur',
    'H.D. Jain College, Ara',
    'H.N.S.B. Janta College, Dhansoi, Buxar',
    'I.D.B.P. Singh College, Garh Nokha',
    'Indra Parashuram Singh Mahavidyalaya, Maidan Kala, Belaon, Kaimur',
    'Indra Parashuram Singh Mahila Mahavidyalaya, Chilbili Kudra, Kaimur',
    'Indu Tapeshwar Singh Mahila College, Bikramganj, Rohtas',
    'J. D. S. Degree College, Diliyan, Tarari, Bhojpur',
    'J.L.N. College, Dehri-on-Sone',
    'Jagdeo Memorial College, Sakari, Kudra',
    'Jagjiwan College, Ara',
    'Jagjiwan College, Dehri-On-Sone, Sasaram',
    'Jan Sahakari D.C. Barap, Garahni, Bhojpur',
    'K.N.S. College, Itarhi Road, Buxar',
    'L.B.G.T. College, Buxar',
    'Lalu Prasad Yadav College, Akodhi, Gola',
    'M.C. College, Chausa, Buxar',
    'M.D.R.P.D.M. College, Bhabhua, Kaimur',
    'M.P. College, Mohania',
    'M.V. College, Buxar',
    'Mahanth Mahadevanand Mahila Mahavidyalya, Ara',
    'Maharaja College, Ara',
    'Mahatma Gandhi College, Lahrabad Peero, Bhojpur',
    'Mahila College, Dalmianagar, Rohtas',
    'Mata Manjharo Ajab Dayal Singh College, Jagdishpur, Bhojpur',
    'Mauni Baba Yamuna Dash Lakharoja Devi Mahila College, Bikarmgang',
    'P.C. College, Buxar',
    'Patel College, Ghushiya Khurd',
    'Payhari Maharaj Ji College, Ara, Bhojpur',
    'Principal B.P. Singh College, Simari',
    'R. S. M. Degree College, Santpur, Dhanupra, Ara',
    'R.M. Devi C.D. Rai College, Nawan Kochas',
    'R.S.D. College, Bhagwanpur, Kaimur',
    'Radha Shanta College, Tilauthoo, Rohtas',
    'Ram Kishor Singh College, Dalmiyangar, Rohtas',
    'Ram Nagina Singh College, Ararua, Akodhi, Karhagar, Rohtas',
    'Ram Narayan Sah Sharvoday College, Ganj Bhadasra, Sasaram, Rohtas',
    'Ramawtar Singh Adarsh Mahavidyalaya, Bijhaura, Buxar',
    'Rohtas Mahila College, Sasaram, Rohtas',
    'S. B. College, Ara',
    'S.M. College, Dumraon',
    'S.N. College, Shahmal Khaira-Deo, Rohtas',
    'S.S.S. College, Dinara, Rohtas',
    'S.S.S. Mahila College, Bhabhua',
    'S.T.S.M. College, Panwari, Bhojpur',
    'S.V.P. College, Bhabua, Kaimur',
    'Sant Shri Brahna Mahila College, Jagdishpur',
    'Seema Kumari College, Itarhi Road, Turkpurwa, Buxar',
    'Shanti Prasad Jain College, Sasaram, Rohtas',
    'Shershah College, Sasaram, Rohtas',
    'Shivgovind Nandlal Singh Degree Mahavidyalay, Sikraul Lock, Dafadihari, Buxar',
    'Shri Shankar College, Sasaram, Rohtas',
    'Shrimati Prabhawati Vidhyabhusan College, Bhabhua',
    'Sidhnath Sah College, At-Baghelwa (Tiyara), Rajpur, Buxar',
    'Sri Tridandi Dev Govt. Degree College, Gautam Nagar, Shahpur, Bhojpur',
    'Sub Divisional Government College, Nauhatta, Rohtas',
    'Swami Shivanand Jee Tirth College, Sasaram, Rohtas',
    'Tapeshwar Singh Indu Mahila Mahavidyalya, Ara, Bhojpur',
    'Tara Shivshankar Degree College, Tiyara, Buxar',
    'Veer Kunwar Singh College, Jagdishpur',
    'Veer Kunwar Singh Mahavidhyalya, Dharupur, Bikramganj, Rohtas',
    'Veer Kunwar Singh Mahila College, Kashi Medinipur, Nasriganj, Rohtas',
  ],
  'Nalanda Open University (NOU), Nalanda': null,
}

export const COLLEGE_OTHER_LABEL = 'Other (Please specify)'
export const collegeOptionsFromList = (items: string[]) => {
  const dedup = Array.from(new Set(items.map((s) => String(s || '').trim()).filter(Boolean)))
  const normalized = dedup
    .filter((x) => x.toLowerCase() !== COLLEGE_OTHER_LABEL.toLowerCase())
    .sort((a, b) => a.localeCompare(b))
  return [...normalized, COLLEGE_OTHER_LABEL].map((v) => ({ value: v, label: v }))
}

export const isOtherCollege = (collegeValue: string) =>
  (collegeValue || '').trim().toLowerCase() === COLLEGE_OTHER_LABEL.toLowerCase() ||
  (collegeValue || '').trim() === OTHER_OPTION_VALUE
