"""DPIIT / government industry sectors for company registration (client spec v1.0)."""

# 57 sectors — value stored in Mongo `industryType` is the display string. "Others" is #57.
DPIIT_INDUSTRY_SECTORS_RAW = (
    "Agriculture & Cooperation",
    "Agriculture and Allied Sectors",
    "AI / ML",
    "Animal Husbandry & Fishing",
    "AR / VR",
    "Art & Culture",
    "Art and Handicrafts",
    "Automobile Sector",
    "Chemicals & Fertilizers",
    "Coal & Mine",
    "Commerce & Industry",
    "Communications & Information Technology",
    "Construction / Architecture / Proptech",
    "Defence",
    "Drone Technology",
    "E-commerce",
    "E-Vehicle",
    "Education & Training",
    "Edu-Tech",
    "Employment & Labour",
    "Energy & Power",
    "Environment & Natural Resources",
    "Environment and Waste Management",
    "Fashion and Apparels",
    "Finance, Banking & Insurance",
    "Finance and Allied Sectors",
    "FMCG",
    "Food & Public Distribution",
    "Food Processing",
    "Forestry & Wildlife",
    "Governance & Administration",
    "Health & Family Welfare",
    "Healthcare",
    "Home Affairs & National Security",
    "HORECA",
    "Housing & Urban Development",
    "HR Services",
    "Information & Broadcasting",
    "International Affairs",
    "IoT / ICT",
    "IT / ITeS",
    "Law & Justice",
    "Manufacturing / Industrial Automation",
    "Media and Entertainment",
    "Packaging and Logistics",
    "People & Organisations",
    "Petroleum, Oil & Natural Gas",
    "Robotics Technology",
    "Rural Development & Panchayati Raj",
    "Science, Technology & Research",
    "Social Justice & Empowerment",
    "Tourism",
    "Transport & Infrastructure",
    "Travel / Tourism & Hospitality",
    "Urban Transportation",
    "Youth Affairs & Sports",
    "Others",
)

_OTHERS = "Others"
_rest = [s for s in DPIIT_INDUSTRY_SECTORS_RAW if s != _OTHERS]
DPIIT_INDUSTRY_SECTORS: tuple[str, ...] = tuple(sorted(_rest, key=lambda x: x.lower())) + (_OTHERS,)
