export const ROUTES = {
  home: '/',
  about: '/about',
  contact: '/contact',
  training: '/training',
  trainingDetail: (id: string) => `/training/${id}`,
  internship: '/internship',
  verify: '/verify',
  login: '/login',
  register: '/register',
  dashboard: '/dashboard',
  myCourses: '/dashboard/courses',
  courseContent: (id: string) => `/dashboard/courses/${id}`,
  invoices: '/dashboard/invoices',
  notifications: '/dashboard/notifications',
  admin: '/admin',
  adminCourses: '/admin/courses',
  adminStudents: '/admin/students',
  adminCertificates: '/admin/certificates',
  adminLeads: '/admin/leads',
  adminPayments: '/admin/payments',
} as const
